"""
noust.core.paths: the one place that knows both names of every directory.

The rule under test is the one that keeps a rename from reopening the trap
of 2026-08-13, when creating a directory moved a populated store to an empty
one: a location that holds WASM's data wins over a new one that would be
empty, until the migration has moved it and left a link.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from noust.core import paths


class TestResolveDir:
    def test_only_the_new_directory(self, tmp_path: Path) -> None:
        new, legacy = tmp_path / "noust", tmp_path / "wasm"
        new.mkdir()
        assert paths.resolve_dir(new, legacy) == new

    def test_only_the_legacy_directory(self, tmp_path: Path) -> None:
        new, legacy = tmp_path / "noust", tmp_path / "wasm"
        legacy.mkdir()
        assert paths.resolve_dir(new, legacy) == legacy

    def test_neither_is_the_new_one(self, tmp_path: Path) -> None:
        new, legacy = tmp_path / "noust", tmp_path / "wasm"
        assert paths.resolve_dir(new, legacy) == new

    def test_both_real_is_the_legacy_one_not_yet_migrated(self, tmp_path: Path) -> None:
        # A package created /etc/noust; the operator's data is still in /etc/wasm.
        new, legacy = tmp_path / "noust", tmp_path / "wasm"
        new.mkdir()
        legacy.mkdir()
        assert paths.resolve_dir(new, legacy) == legacy

    def test_a_legacy_symlink_means_migrated(self, tmp_path: Path) -> None:
        new, legacy = tmp_path / "noust", tmp_path / "wasm"
        new.mkdir()
        legacy.symlink_to(new)
        assert paths.resolve_dir(new, legacy) == new


class TestEnvironment:
    def test_the_noust_spelling_wins(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("NOUST_WEB_STATE_DIR", "/new")
        monkeypatch.setenv("WASM_WEB_STATE_DIR", "/old")
        assert paths.getenv("WEB_STATE_DIR") == "/new"

    def test_the_wasm_spelling_is_still_read(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.delenv("NOUST_WEB_STATE_DIR", raising=False)
        monkeypatch.setenv("WASM_WEB_STATE_DIR", "/old")
        assert paths.getenv("WEB_STATE_DIR") == "/old"

    def test_neither_is_the_default(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.delenv("NOUST_WEB_STATE_DIR", raising=False)
        monkeypatch.delenv("WASM_WEB_STATE_DIR", raising=False)
        assert paths.getenv("WEB_STATE_DIR", "fallback") == "fallback"


class TestUnits:
    @pytest.mark.parametrize(
        "name",
        [
            "noust-web",
            "wasm-web",
            "noust-monitor",
            "wasm-monitor",
            "noust-previews",
            "wasm-previews",
            "noust-cron-nightly",
            "wasm-cron-nightly",
            "noust-backup-shop-example-com",
            "wasm-backup-shop-example-com",
        ],
    )
    def test_own_units_under_either_name(self, name: str) -> None:
        assert paths.is_own_unit_name(name)

    @pytest.mark.parametrize("name", ["shop-example-com", "wasm-shop-example-com", "nginx"])
    def test_application_and_system_units_are_not_own(self, name: str) -> None:
        assert not paths.is_own_unit_name(name)

    def test_either_marker_is_recognised(self) -> None:
        assert paths.carries_unit_marker("# Generated by Noust\n[Unit]\n")
        assert paths.carries_unit_marker("# Generated by WASM\n[Unit]\n")
        assert not paths.carries_unit_marker("[Unit]\nDescription=hand made\n")


class TestCameFromWasm:
    def test_a_fresh_install_did_not(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(paths, "MIGRATION_RECORD", tmp_path / "record.json")
        monkeypatch.setattr(paths, "LEGACY_CONFIG_DIR", tmp_path / "etc-wasm")
        monkeypatch.setattr(paths, "LEGACY_STATE_DIR", tmp_path / "lib-wasm")
        assert not paths.came_from_wasm()

    def test_a_migrated_server_did(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        record = tmp_path / "record.json"
        record.write_text("[]")
        monkeypatch.setattr(paths, "MIGRATION_RECORD", record)
        monkeypatch.setattr(paths, "LEGACY_CONFIG_DIR", tmp_path / "etc-wasm")
        monkeypatch.setattr(paths, "LEGACY_STATE_DIR", tmp_path / "lib-wasm")
        assert paths.came_from_wasm()

    def test_a_server_not_migrated_yet_did(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(paths, "MIGRATION_RECORD", tmp_path / "record.json")
        monkeypatch.setattr(paths, "LEGACY_CONFIG_DIR", tmp_path / "etc-wasm")
        monkeypatch.setattr(paths, "LEGACY_STATE_DIR", tmp_path / "lib-wasm")
        (tmp_path / "etc-wasm").mkdir()
        assert paths.came_from_wasm()


def test_repository_overrides_prefer_the_new_name(tmp_path: Path) -> None:
    from noust.deployers.helpers.nginx_config import NginxConfigBuilder

    builder = NginxConfigBuilder()
    (tmp_path / "wasm.nginx.yaml").write_text("routes: []\n")
    assert builder.detect(tmp_path) == tmp_path / "wasm.nginx.yaml"
    (tmp_path / "noust.nginx.yaml").write_text("routes: []\n")
    assert builder.detect(tmp_path) == tmp_path / "noust.nginx.yaml"
