"""
The move of a WASM 2.x server onto Noust's names.

Every test builds a whole 2.x machine under ``tmp_path`` - /etc/wasm with its
config.yaml, /var/lib/wasm with a store in write-ahead-log mode, backups, the
nginx upstreams directory and the sites that include it, PHP-FPM pools, and
WASM's own units - and runs the real migration against it through a
FakeRunner. The properties asserted are the ones whose absence would lose an
operator's data or take their sites down: nothing is copied, the store is
never left behind an empty one, every failure is undone, and a run stopped
halfway is finished by the next.
"""

from __future__ import annotations

import errno
import json
import os
import sqlite3
from pathlib import Path

import pytest

import noust.core.migrate_from_wasm as migration
from noust.core import paths
from noust.core.fs import RealFileSystem
from noust.core.migrate_from_wasm import Layout, Migrator, needs_migration
from noust.core.runner import FakeRunner

APPS = ("shop-example-com", "blog-example-com")


def make_layout(root: Path) -> Layout:
    """
    Build a layout whose every path lives under ``root``.

    Args:
        root: The fake filesystem root.

    Returns:
        The layout.
    """
    return Layout(
        config_dir=root / "etc/noust",
        legacy_config_dir=root / "etc/wasm",
        state_dir=root / "var/lib/noust",
        legacy_state_dir=root / "var/lib/wasm",
        backup_dir=root / "var/backups/noust",
        legacy_backup_dir=root / "var/backups/wasm",
        user_data_dir=root / "root/.local/share/noust",
        legacy_user_data_dir=root / "root/.local/share/wasm",
        upstreams_dir=root / "etc/nginx/noust-upstreams",
        legacy_upstreams_dir=root / "etc/nginx/wasm-upstreams",
        nginx_site_dirs=(root / "etc/nginx/sites-available", root / "etc/nginx/sites-enabled"),
        systemd_dir=root / "etc/systemd/system",
        php_root=root,
        lock_file=root / "run/noust-migrate.lock",
    )


def make_store(path: Path, apps: tuple[str, ...] = APPS) -> None:
    """
    Create a store in write-ahead-log mode with a few applications in it.

    Args:
        path: The database file.
        apps: Application names to insert.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(path)
    connection.execute("PRAGMA journal_mode=WAL")
    connection.execute("CREATE TABLE apps (name TEXT)")
    connection.executemany("INSERT INTO apps VALUES (?)", [(a,) for a in apps])
    connection.commit()
    connection.close()


def app_names(path: Path) -> list[str]:
    """
    Read the applications a store holds.

    Args:
        path: The database file.

    Returns:
        Their names, sorted.
    """
    connection = sqlite3.connect(path)
    try:
        return sorted(row[0] for row in connection.execute("SELECT name FROM apps"))
    finally:
        connection.close()


WEB_UNIT = """# The WASM console, kept running across reboots.
# Generated by WASM. Written by 'wasm web enable', removed by 'wasm web disable'.

[Unit]
Description=WASM console

[Service]
ExecStart=/usr/bin/wasm web start --under-systemd --host 127.0.0.1 --port 8080 --tls-cert /etc/wasm/panel-tls/panel.crt
SyslogIdentifier=wasm-web

[Install]
WantedBy=multi-user.target
"""

MONITOR_UNIT = """# WASM process monitor
# Generated by WASM. Do not edit; reinstall with: wasm monitor install

[Unit]
Description=WASM process and resource monitor

[Service]
ExecStart=/usr/local/bin/wasm monitor run
StateDirectory=wasm
LogsDirectory=wasm
SyslogIdentifier=wasm-monitor
"""

CRON_SERVICE = """# WASM cron job nightly
# Generated by WASM

[Unit]
Description=WASM cron job nightly

[Service]
Type=oneshot
ExecStart=/usr/bin/php /var/www/apps/shop-example-com/artisan schedule:run
"""

CRON_TIMER = """# WASM cron timer for nightly
# Generated by WASM

[Unit]
Description=WASM cron timer for nightly

[Timer]
OnCalendar=daily
Unit=wasm-cron-nightly.service

[Install]
WantedBy=timers.target
"""

APP_UNIT = """# Systemd service for shop.example.com
# Generated by WASM

[Service]
ExecStart=/usr/bin/node server.js
"""


@pytest.fixture
def machine(tmp_path: Path) -> Layout:
    """
    A WASM 2.x server, whole, under ``tmp_path``.

    Returns:
        Its layout.
    """
    layout = make_layout(tmp_path)
    layout.legacy_config_dir.mkdir(parents=True)
    (layout.legacy_config_dir / "config.yaml").write_text(
        "# Operator's comment, kept\n"
        "apps_directory: /var/www/apps\n"
        "backup:\n"
        "  directory: /var/backups/wasm\n"
        "  max_per_app: 10\n"
        "logging:\n"
        "  file: /var/log/wasm/wasm.log\n"
        "monitor:\n"
        "  log_file: '/var/log/wasm/monitor.log'\n"
    )
    (layout.legacy_config_dir / "web-secret").write_text("signing key")
    make_store(layout.legacy_state_dir / "wasm.db")
    (layout.legacy_state_dir / "secrets").mkdir()
    (layout.legacy_state_dir / "secrets" / "shop").write_text("s3cret")
    layout.legacy_backup_dir.mkdir(parents=True)
    (layout.legacy_backup_dir / "shop-example-com-20260901.tar.gz").write_text("archive")

    layout.legacy_upstreams_dir.mkdir(parents=True)
    (layout.legacy_upstreams_dir / "shop-example-com.conf").write_text("upstream wasm_bg_shop {}\n")
    available, enabled = layout.nginx_site_dirs
    available.mkdir(parents=True)
    enabled.mkdir(parents=True)
    site = available / "shop.example.com"
    site.write_text(
        f"include {layout.legacy_upstreams_dir}/shop-example-com.conf;\n"
        "server { server_name shop.example.com; }\n"
    )
    (enabled / "shop.example.com").symlink_to(site)
    (available / "static.example.com").write_text("server { root /srv; }\n")

    layout.systemd_dir.mkdir(parents=True)
    (layout.systemd_dir / "wasm-web.service").write_text(WEB_UNIT)
    (layout.systemd_dir / "wasm-monitor.service").write_text(MONITOR_UNIT)
    (layout.systemd_dir / "wasm-cron-nightly.service").write_text(CRON_SERVICE)
    (layout.systemd_dir / "wasm-cron-nightly.timer").write_text(CRON_TIMER)
    # An application's unit from before 0.14.1: it keeps its name.
    (layout.systemd_dir / "wasm-shop-example-com.service").write_text(APP_UNIT)
    # Somebody's own unit that happens to share the prefix: not WASM's.
    (layout.systemd_dir / "wasm-backup-handmade.service").write_text("[Service]\n")
    (tmp_path / "run").mkdir()
    return layout


def migrator(layout: Layout, runner: FakeRunner, lines: list[str] | None = None) -> Migrator:
    """
    Build a migrator over a fake machine.

    Args:
        layout: The machine.
        runner: Answers systemctl, nginx and php-fpm.
        lines: Collects the announced steps.

    Returns:
        The migrator.
    """
    return Migrator(
        layout,
        runner=runner,
        fs=RealFileSystem(),
        announce=(lines.append if lines is not None else None),
        noust_executable="/usr/bin/noust",
    )


def inactive(runner: FakeRunner, *units: str) -> FakeRunner:
    """
    Make systemd report units as neither enabled nor running.

    Args:
        runner: The runner to script.
        units: Unit file names.

    Returns:
        The runner.
    """
    for unit in units:
        runner.script(["systemctl", "is-active", "--quiet", unit], exit_code=3)
        runner.script(["systemctl", "is-enabled", "--quiet", unit], exit_code=1)
    return runner


def quiet_runner() -> FakeRunner:
    """
    A machine where every unit is enabled and running but the cron job's
    service, which only its timer starts and which is not running now.

    Returns:
        The runner.
    """
    return inactive(FakeRunner(), "wasm-cron-nightly.service")


class TestFullMigration:
    """A 2.x server, migrated in one run."""

    def test_every_directory_moves_and_leaves_a_link(self, machine: Layout) -> None:
        report = migrator(machine, quiet_runner()).run()

        assert report.complete, report.as_dict()
        for legacy, new in (
            (machine.legacy_config_dir, machine.config_dir),
            (machine.legacy_state_dir, machine.state_dir),
            (machine.legacy_backup_dir, machine.backup_dir),
            (machine.legacy_upstreams_dir, machine.upstreams_dir),
        ):
            assert new.is_dir() and not new.is_symlink()
            assert legacy.is_symlink()
            assert legacy.resolve() == new.resolve()
        assert (machine.config_dir / "web-secret").read_text() == "signing key"
        assert (machine.state_dir / "secrets" / "shop").read_text() == "s3cret"
        # A backup path recorded as /var/backups/wasm/... still opens.
        recorded = machine.legacy_backup_dir / "shop-example-com-20260901.tar.gz"
        assert recorded.read_text() == "archive"

    def test_the_store_is_renamed_with_every_row(self, machine: Layout) -> None:
        migrator(machine, quiet_runner()).run()

        store = machine.state_dir / paths.STORE_NAME
        assert app_names(store) == sorted(APPS)
        assert not (machine.state_dir / paths.LEGACY_STORE_NAME).exists()
        assert not Path(f"{machine.state_dir / paths.LEGACY_STORE_NAME}-wal").exists()

    def test_config_defaults_are_rewritten_and_the_rest_kept(self, machine: Layout) -> None:
        migrator(machine, quiet_runner()).run()

        text = (machine.config_dir / "config.yaml").read_text()
        assert "# Operator's comment, kept" in text
        assert "directory: /var/backups/noust\n" in text
        assert "file: /var/log/noust/noust.log\n" in text
        assert "log_file: '/var/log/noust/monitor.log'\n" in text
        assert "max_per_app: 10" in text
        assert (machine.config_dir / "config.yaml").stat().st_mode & 0o777 == 0o600

    def test_sites_are_repointed_and_nginx_tested_then_reloaded(self, machine: Layout) -> None:
        runner = quiet_runner()
        migrator(machine, runner).run()

        site = machine.nginx_site_dirs[0] / "shop.example.com"
        assert f"include {machine.upstreams_dir}/shop-example-com.conf;" in site.read_text()
        # The enabling symlink was not replaced by a copy.
        assert (machine.nginx_site_dirs[1] / "shop.example.com").is_symlink()
        test = runner.calls.index(("nginx", "-t"))
        reload = runner.calls.index(("systemctl", "reload", "nginx"))
        assert test < reload

    def test_units_are_replaced_in_the_same_state(self, machine: Layout) -> None:
        runner = quiet_runner()
        migrator(machine, runner).run()

        units = machine.systemd_dir
        for old in ("wasm-web.service", "wasm-monitor.service", "wasm-cron-nightly.timer"):
            assert not (units / old).exists()
        web = (units / "noust-web.service").read_text()
        assert "# Generated by Noust." in web
        assert "Generated by WASM" not in web
        assert "ExecStart=/usr/bin/noust web start --under-systemd" in web
        assert "--tls-cert /etc/noust/panel-tls/panel.crt" in web
        assert "SyslogIdentifier=noust-web" in web
        assert "Description=Noust console" in web
        monitor = (units / "noust-monitor.service").read_text()
        assert "StateDirectory=noust\nLogsDirectory=noust\n" in monitor
        assert "ExecStart=/usr/bin/noust monitor run" in monitor
        timer = (units / "noust-cron-nightly.timer").read_text()
        assert "Unit=noust-cron-nightly.service" in timer
        service = (units / "noust-cron-nightly.service").read_text()
        assert "ExecStart=/usr/bin/php /var/www/apps/shop-example-com/artisan" in service

        # Enabled and started as the old ones were (all reported active here,
        # but the cron job's service, which only a timer starts).
        assert ("systemctl", "enable", "noust-web.service") in runner.calls
        assert ("systemctl", "start", "noust-web.service") in runner.calls
        assert ("systemctl", "enable", "noust-cron-nightly.timer") in runner.calls
        assert ("systemctl", "start", "noust-cron-nightly.timer") in runner.calls
        assert ("systemctl", "start", "noust-cron-nightly.service") not in runner.calls
        assert ("systemctl", "disable", "wasm-web.service") in runner.calls

    def test_the_old_console_stops_before_the_new_one_starts(self, machine: Layout) -> None:
        runner = quiet_runner()
        migrator(machine, runner).run()

        stops = [
            i for i, c in enumerate(runner.calls) if c == ("systemctl", "stop", "wasm-web.service")
        ]
        start = runner.calls.index(("systemctl", "start", "noust-web.service"))
        assert stops and min(stops) < start
        # It was not started again under its old name: the new one replaced it.
        assert ("systemctl", "start", "wasm-web.service") not in runner.calls

    def test_application_and_foreign_units_keep_their_names(self, machine: Layout) -> None:
        migrator(machine, quiet_runner()).run()

        assert (machine.systemd_dir / "wasm-shop-example-com.service").read_text() == APP_UNIT
        assert (machine.systemd_dir / "wasm-backup-handmade.service").exists()
        assert not (machine.systemd_dir / "noust-backup-handmade.service").exists()

    def test_a_record_is_left_for_the_console(self, machine: Layout) -> None:
        migrator(machine, quiet_runner()).run()

        history = json.loads(machine.record.read_text())
        assert history[-1]["complete"] is True
        assert any(step["kind"] == "store" for step in history[-1]["steps"])

    def test_one_line_per_step_is_announced(self, machine: Layout) -> None:
        lines: list[str] = []
        migrator(machine, quiet_runner(), lines).run()

        assert any("renamed" in line and "etc/wasm" in line for line in lines)
        assert any("wasm-web" in line and "noust-web" in line for line in lines)

    def test_running_again_does_nothing(self, machine: Layout) -> None:
        migrator(machine, quiet_runner()).run()
        assert not needs_migration(machine)

        runner = quiet_runner()
        report = migrator(machine, runner).run()
        assert report.steps == []
        assert runner.calls == []


class TestDryRun:
    """A plan changes nothing."""

    def test_plan_lists_every_step_and_touches_nothing(self, machine: Layout) -> None:
        runner = quiet_runner()
        before = sorted(str(p) for p in machine.legacy_config_dir.parent.parent.rglob("*"))

        report = migrator(machine, runner).plan()

        after = sorted(str(p) for p in machine.legacy_config_dir.parent.parent.rglob("*"))
        assert before == after
        assert runner.calls == []
        kinds = [step.kind for step in report.steps]
        assert kinds.count("directory") == 3
        assert {"store", "config", "nginx", "unit"} <= set(kinds)
        assert all(step.status == "pending" for step in report.steps)


class TestRefusals:
    """What is not safe to do is not done, and is explained."""

    def test_a_different_filesystem_is_refused_and_nothing_copied(
        self, machine: Layout, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        state = machine.legacy_state_dir

        def same(first: Path, second: Path) -> bool:
            return first != state

        monkeypatch.setattr(migration, "same_filesystem", same)
        report = migrator(machine, quiet_runner()).run()

        refused = [s for s in report.steps if s.status == "refused"]
        assert any("different filesystems" in s.detail for s in refused)
        assert state.is_dir() and not state.is_symlink()
        assert not machine.state_dir.exists()
        # The store was renamed in place, where the resolution still finds it.
        assert app_names(state / paths.STORE_NAME) == sorted(APPS)
        # The units expect the new state directory, so they were left alone.
        assert (machine.systemd_dir / "wasm-monitor.service").exists()
        assert not (machine.systemd_dir / "noust-monitor.service").exists()
        assert not report.complete

    def test_a_cross_device_rename_is_undone(
        self, machine: Layout, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        class CrossDevice(RealFileSystem):
            def rename(self, source: Path, destination: Path) -> None:
                if source == machine.legacy_backup_dir:
                    raise OSError(errno.EXDEV, "Invalid cross-device link")
                super().rename(source, destination)

        report = Migrator(
            machine, runner=quiet_runner(), fs=CrossDevice(), noust_executable="/usr/bin/noust"
        ).run()

        failed = [s for s in report.steps if s.status == "failed"]
        assert failed and "different filesystems" in failed[0].detail
        assert machine.legacy_backup_dir.is_dir() and not machine.legacy_backup_dir.is_symlink()
        assert not os.path.lexists(migration._pending_link(machine.legacy_backup_dir))
        # backup.directory still names the backups where they are.
        text = (machine.config_dir / "config.yaml").read_text()
        assert "directory: /var/backups/wasm\n" in text

    def test_a_store_held_open_is_not_moved(self, machine: Layout) -> None:
        holder = sqlite3.connect(machine.legacy_state_dir / "wasm.db")
        holder.execute("INSERT INTO apps VALUES ('late')")
        holder.commit()
        try:
            report = migrator(machine, quiet_runner()).run()
        finally:
            holder.close()

        store = next(s for s in report.steps if s.kind == "store")
        assert store.status == "refused"
        assert "open" in store.detail
        assert (machine.legacy_state_dir / "wasm.db").exists()
        assert app_names(machine.legacy_state_dir / "wasm.db") == sorted((*APPS, "late"))

    def test_a_noust_directory_a_package_created_is_made_way_for(self, machine: Layout) -> None:
        machine.config_dir.mkdir(parents=True)
        (machine.config_dir / "config.yaml").write_text("# packaged default\n")
        machine.state_dir.mkdir(parents=True)

        report = migrator(machine, quiet_runner()).run()

        assert report.complete
        assert "Operator's comment" in (machine.config_dir / "config.yaml").read_text()
        aside = list(machine.config_dir.parent.glob("noust.before-migration-*"))
        assert len(aside) == 1
        assert (aside[0] / "config.yaml").read_text() == "# packaged default\n"
        assert app_names(machine.state_dir / paths.STORE_NAME) == sorted(APPS)

    def test_a_timer_job_running_right_now_is_left_for_later(self, machine: Layout) -> None:
        runner = FakeRunner()  # every unit reports active, the job's service included
        report = migrator(machine, runner).run()

        cron = next(s for s in report.steps if "wasm-cron-nightly" in s.description)
        assert cron.status == "refused"
        assert (machine.systemd_dir / "wasm-cron-nightly.timer").exists()


class TestUndo:
    """Every failure puts back what was there."""

    def test_a_unit_that_cannot_be_enabled_is_put_back(self, machine: Layout) -> None:
        runner = quiet_runner()
        runner.script(
            ["systemctl", "enable", "noust-cron-nightly.timer"],
            exit_code=1,
            stderr="Failed to enable unit: Unit file noust-cron-nightly.timer is masked.",
        )

        report = migrator(machine, runner).run()

        step = next(s for s in report.steps if "wasm-cron-nightly" in s.description)
        assert step.status == "failed"
        assert "masked" in step.detail
        assert (machine.systemd_dir / "wasm-cron-nightly.timer").read_text() == CRON_TIMER
        assert not (machine.systemd_dir / "noust-cron-nightly.timer").exists()
        assert not (machine.systemd_dir / "noust-cron-nightly.service").exists()
        # Restored in the state it had: enabled and running again.
        last_enable = max(
            i
            for i, c in enumerate(runner.calls)
            if c == ("systemctl", "enable", "wasm-cron-nightly.timer")
        )
        failed_enable = runner.calls.index(("systemctl", "enable", "noust-cron-nightly.timer"))
        assert last_enable > failed_enable
        assert ("systemctl", "start", "wasm-cron-nightly.timer") in runner.calls
        # The other units were still migrated.
        assert (machine.systemd_dir / "noust-web.service").exists()

    def test_a_console_that_does_not_come_up_is_put_back_and_restarted(
        self, machine: Layout
    ) -> None:
        runner = quiet_runner()
        runner.script(["systemctl", "is-active", "--quiet", "noust-web.service"], exit_code=3)
        runner.script(
            ["journalctl", "-u", "noust-web.service"], stdout="bind: address already in use"
        )

        report = migrator(machine, runner).run()

        step = next(s for s in report.steps if "wasm-web" in s.description)
        assert step.status == "failed"
        assert "address already in use" in step.detail
        assert (machine.systemd_dir / "wasm-web.service").exists()
        assert not (machine.systemd_dir / "noust-web.service").exists()
        assert runner.calls[-1] != ("systemctl", "stop", "wasm-web.service")
        assert ("systemctl", "start", "wasm-web.service") in runner.calls

    def test_nginx_rejecting_the_includes_restores_every_site(self, machine: Layout) -> None:
        site = machine.nginx_site_dirs[0] / "shop.example.com"
        original = site.read_text()
        runner = quiet_runner()
        runner.script(["nginx", "-t"], exit_code=1, stderr="nginx: [emerg] unexpected end of file")

        report = migrator(machine, runner).run()

        step = next(s for s in report.steps if s.kind == "nginx")
        assert step.status == "failed"
        assert "[emerg] unexpected end of file" in step.detail
        assert site.read_text() == original
        assert ("systemctl", "reload", "nginx") not in runner.calls
        # The includes keep loading through the link.
        assert (machine.legacy_upstreams_dir / "shop-example-com.conf").is_file()


class TestInterrupted:
    """A run stopped between two steps is finished by the next."""

    def test_a_directory_renamed_before_its_link_was_placed(self, machine: Layout) -> None:
        # What a run stopped right after renaming /etc/wasm leaves behind.
        pending = migration._pending_link(machine.legacy_config_dir)
        pending.symlink_to(machine.config_dir)
        machine.legacy_config_dir.rename(machine.config_dir)
        assert needs_migration(machine)

        report = migrator(machine, quiet_runner()).run()

        assert report.complete
        assert machine.legacy_config_dir.is_symlink()
        assert not os.path.lexists(pending)

    def test_a_store_renamed_before_its_directory_moved(self, machine: Layout) -> None:
        (machine.legacy_state_dir / "wasm.db").rename(machine.legacy_state_dir / "noust.db")

        report = migrator(machine, quiet_runner()).run()

        assert report.complete
        assert app_names(machine.state_dir / paths.STORE_NAME) == sorted(APPS)

    def test_a_run_that_crashed_mid_way_is_completed(
        self, machine: Layout, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        class Crash(Exception):
            pass

        class Crashing(RealFileSystem):
            def rename(self, source: Path, destination: Path) -> None:
                super().rename(source, destination)
                if destination == machine.state_dir:
                    raise Crash

        with pytest.raises(Crash):
            Migrator(
                machine, runner=quiet_runner(), fs=Crashing(), noust_executable="/usr/bin/noust"
            ).run()
        assert machine.state_dir.is_dir()
        assert not machine.legacy_state_dir.exists()

        report = migrator(machine, quiet_runner()).run()

        assert report.complete
        assert machine.legacy_state_dir.is_symlink()
        assert app_names(machine.state_dir / paths.STORE_NAME) == sorted(APPS)
        assert (machine.systemd_dir / "noust-web.service").exists()


class TestPhpPools:
    """PHP-FPM pools move with their sockets, without dropping a request."""

    @pytest.fixture
    def php(self, machine: Layout) -> Path:
        root = machine.php_root
        pool_dir = root / "etc/php/8.3/fpm/pool.d"
        pool_dir.mkdir(parents=True)
        (root / "usr/sbin").mkdir(parents=True)
        (root / "usr/sbin/php-fpm8.3").write_text("")
        (pool_dir / "wasm-wp-example-com.conf").write_text(
            "; Generated by WASM\n[wasm-wp-example-com]\nlisten = /run/php/wasm-wp-example-com.sock\n"
        )
        (pool_dir / "wasm-old-example-com.conf.disabled").write_text(
            "[wasm-old-example-com]\nlisten = /run/php/wasm-old-example-com.sock\n"
        )
        (pool_dir / "www.conf").write_text("[www]\n")
        (machine.nginx_site_dirs[0] / "wp.example.com").write_text(
            "location ~ \\.php$ { fastcgi_pass unix:/run/php/wasm-wp-example-com.sock; }\n"
        )
        return pool_dir

    def test_pools_and_sites_are_renamed_new_before_old_goes(
        self, machine: Layout, php: Path
    ) -> None:
        runner = quiet_runner()
        report = migrator(machine, runner).run()

        step = next(s for s in report.steps if s.kind == "php")
        assert step.status == "done", step.detail
        pool = (php / "noust-wp-example-com.conf").read_text()
        assert "[noust-wp-example-com]" in pool
        assert "listen = /run/php/noust-wp-example-com.sock" in pool
        assert "Generated by Noust" in pool
        assert not (php / "wasm-wp-example-com.conf").exists()
        assert (php / "noust-old-example-com.conf.disabled").exists()
        assert (php / "www.conf").exists()
        site = (machine.nginx_site_dirs[0] / "wp.example.com").read_text()
        assert "unix:/run/php/noust-wp-example-com.sock" in site
        # FPM serves both sockets before nginx is pointed at the new one.
        fpm_reload = runner.calls.index(("systemctl", "reload-or-restart", "php8.3-fpm"))
        nginx_reloads = [
            i for i, c in enumerate(runner.calls) if c == ("systemctl", "reload", "nginx")
        ]
        assert any(i > fpm_reload for i in nginx_reloads)

    def test_fpm_rejecting_the_pools_removes_them_and_keeps_the_old(
        self, machine: Layout, php: Path
    ) -> None:
        runner = quiet_runner()
        runner.script(["/usr/sbin/php-fpm8.3", "-t"], exit_code=78, stderr="ERROR: bad pool")

        report = migrator(machine, runner).run()

        step = next(s for s in report.steps if s.kind == "php")
        assert step.status == "failed"
        assert "bad pool" in step.detail
        assert (php / "wasm-wp-example-com.conf").exists()
        assert not (php / "noust-wp-example-com.conf").exists()
        site = (machine.nginx_site_dirs[0] / "wp.example.com").read_text()
        assert "wasm-wp-example-com.sock" in site


class TestAutomaticRun:
    """Who migrates on their own, and who does not."""

    @pytest.fixture(autouse=True)
    def as_root(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(migration.os, "geteuid", lambda: 0)

    def test_an_operators_privileged_command_migrates(self) -> None:
        assert migration.should_run_automatically(["list"], {})

    @pytest.mark.parametrize(
        ("argv", "environ"),
        [
            (["web", "start", "--under-systemd"], {"INVOCATION_ID": "abc"}),
            (["--dry-run", "list"], {}),
            (["list"], {"_NOUST_COMPLETE": "bash_complete"}),
            (["list"], {"_WASM_COMPLETE": "bash_complete"}),
            (["migrate-from-wasm"], {}),
            (["list"], {migration.DISABLE_ENV: "1"}),
        ],
    )
    def test_what_never_migrates_on_its_own(self, argv: list[str], environ: dict[str, str]) -> None:
        assert not migration.should_run_automatically(argv, environ)

    def test_an_unprivileged_command_never_migrates(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(migration.os, "geteuid", lambda: 1000)
        assert not migration.should_run_automatically(["list"], {})

    def test_a_failing_migration_lets_the_command_run(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(migration, "should_run_automatically", lambda argv: True)
        monkeypatch.setattr(migration, "needs_migration", lambda: True)

        def explode(self: Migrator) -> None:
            raise migration.MigrationError("lock held")

        monkeypatch.setattr(Migrator, "run", explode)
        lines: list[str] = []

        assert migration.run_automatically(["list"], lines.append) is None
        assert any("noust migrate-from-wasm" in line for line in lines)
