# Copyright (c) 2024-2026 Yago Lopez Prado
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Tests for what the web server layer gained in 3.2 to serve Docker Compose.

Three things are pinned, each one the chokepoint a later flow leans on:

- **Servers files.** ``/etc/nginx/noust-upstreams/<app>/<service>.servers``
  holds only ``server 127.0.0.1:<port>;`` lines, so one file can be included
  from an upstream block Noust wrote or from one the operator wrote. The
  relay of a Compose service moves traffic by rewriting it, so a write is
  atomic, goes through the filesystem seam (a dry run writes nothing) and
  never lands through a symlink, since Noust writes it as root.
- **Site names.** A site the operator named ``proggest`` serves
  ``proggest.es``; ``config_path`` is the only place a domain becomes a file
  name, so it is the one that has to know.
- **The list.** The sites list is the union of the store and what is in
  ``sites-available``: a hand-written site must not vanish from it the moment
  Noust has written one of its own.
"""

from __future__ import annotations

import os
import stat
from collections.abc import Iterator
from dataclasses import replace
from pathlib import Path
from typing import Any

import pytest

from noust.central import RoleError
from noust.core.config import Config
from noust.core.exceptions import (
    DomainError,
    NginxError,
    NoustError,
    SecurityError,
    ValidationError,
)
from noust.core.fs import DryRunFileSystem, RecordingFileSystem, set_fs
from noust.core.runner import FakeRunner
from noust.core.store import App, NoustStore, Site, StoreError, get_store
from noust.core.utils import domain_to_app_name
from noust.managers import webserver
from noust.managers.apache_manager import ApacheManager
from noust.managers.nginx_manager import NginxManager
from noust.managers.webserver import APACHE_BACKEND, NGINX_BACKEND

NOUST_SITE = "# Generated by Noust\nserver {\n    listen 80;\n    server_name {domain};\n}\n"


@pytest.fixture
def upstreams(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """The directory of the servers files, redirected into the test."""
    directory = tmp_path / "etc/nginx/noust-upstreams"
    monkeypatch.setattr(webserver, "NGINX_UPSTREAMS_DIR", directory)
    return directory


@pytest.fixture
def store() -> Iterator[NoustStore]:
    """The process-wide store, at the location conftest redirects it to."""
    NoustStore.reset_instance()
    instance = get_store()
    yield instance
    NoustStore.reset_instance()


@pytest.fixture
def nginx(tmp_path: Path, runner: FakeRunner, upstreams: Path) -> NginxManager:
    """An nginx manager over a temporary configuration tree."""
    return NginxManager(
        backend=replace(
            NGINX_BACKEND,
            sites_available=tmp_path / "etc/nginx/sites-available",
            sites_enabled=tmp_path / "etc/nginx/sites-enabled",
            upstreams_dir=upstreams,
        )
    )


@pytest.fixture
def apache(tmp_path: Path, runner: FakeRunner) -> ApacheManager:
    """An apache manager over a temporary configuration tree."""
    return ApacheManager(
        backend=replace(
            APACHE_BACKEND,
            sites_available=tmp_path / "etc/apache2/sites-available",
            sites_enabled=tmp_path / "etc/apache2/sites-enabled",
        )
    )


@pytest.fixture
def hub(monkeypatch: pytest.MonkeyPatch) -> Iterator[None]:
    """Make this Noust a hub, which deploys and writes no sites itself."""
    monkeypatch.setenv("NOUST_CENTRAL_ROLE", "hub")
    Config.reset_instance()
    yield
    Config.reset_instance()


def make_app(store: NoustStore, domain: str, *, site_name: str | None = None) -> App:
    """Record an application, with the site file name the adoption would store."""
    store.create_app(App(domain=domain, app_type="nodejs", port=3000, app_path=f"/srv/{domain}"))
    if site_name is not None:
        assert store.set_app_site_name(domain, site_name)
    found = store.get_app(domain)
    assert found is not None
    return found


# ---------------------------------------------------------------------------
# servers_file
# ---------------------------------------------------------------------------


class TestServersFile:
    """The path of a servers file is one app directory and one service file."""

    def test_is_one_directory_per_app_under_the_upstreams_directory(self, upstreams: Path) -> None:
        assert webserver.servers_file("proggest-es", "backend") == (
            upstreams / "proggest-es" / "backend.servers"
        )

    @pytest.mark.parametrize(
        "app_name",
        ["..", "../etc", "a/b", "/etc", "", "evil\nname", "evil name", "evil\x00"],
    )
    def test_refuses_an_app_name_that_is_not_one_inert_component(
        self, upstreams: Path, app_name: str
    ) -> None:
        with pytest.raises(ValidationError):
            webserver.servers_file(app_name, "backend")

    @pytest.mark.parametrize(
        "service",
        ["..", "../backend", "a/b", "/etc/passwd", "", "back end", "evil\nname", ".hidden"],
    )
    def test_refuses_a_service_name_that_is_not_one_inert_component(
        self, upstreams: Path, service: str
    ) -> None:
        with pytest.raises(ValidationError):
            webserver.servers_file("proggest-es", service)

    def test_accepts_the_names_compose_gives_services(self, upstreams: Path) -> None:
        path = webserver.servers_file("proggest-es", "web_api-2.v1")

        assert path.name == "web_api-2.v1.servers"

    def test_refuses_an_app_directory_that_is_a_link_out_of_the_tree(
        self, upstreams: Path, tmp_path: Path
    ) -> None:
        outside = tmp_path / "elsewhere"
        outside.mkdir()
        upstreams.mkdir(parents=True)
        (upstreams / "proggest-es").symlink_to(outside)

        with pytest.raises(SecurityError):
            webserver.servers_file("proggest-es", "backend")


# ---------------------------------------------------------------------------
# write_servers
# ---------------------------------------------------------------------------


class TestWriteServers:
    """A servers file holds exactly the loopback servers it was given."""

    def test_writes_only_server_lines(self, upstreams: Path) -> None:
        webserver.write_servers("proggest-es", "backend", [3001])

        path = upstreams / "proggest-es" / "backend.servers"
        assert path.read_text() == "server 127.0.0.1:3001;\n"

    def test_writes_every_port_in_the_order_given(self, upstreams: Path) -> None:
        webserver.write_servers("proggest-es", "backend", [3002, 3001])

        path = upstreams / "proggest-es" / "backend.servers"
        assert path.read_text() == "server 127.0.0.1:3002;\nserver 127.0.0.1:3001;\n"

    def test_replaces_what_was_there(self, upstreams: Path) -> None:
        webserver.write_servers("proggest-es", "backend", [3001])
        webserver.write_servers("proggest-es", "backend", [3002])

        assert webserver.read_servers("proggest-es", "backend") == [3002]

    def test_is_world_readable_like_the_rest_of_the_web_server_configuration(
        self, upstreams: Path
    ) -> None:
        webserver.write_servers("proggest-es", "backend", [3001])

        mode = stat.S_IMODE((upstreams / "proggest-es" / "backend.servers").stat().st_mode)
        assert mode == 0o644

    def test_goes_through_the_filesystem_seam(self, upstreams: Path) -> None:
        recording = RecordingFileSystem()
        set_fs(recording)

        webserver.write_servers("proggest-es", "backend", [3001])

        written = [path for kind, path in recording.changes if kind == "write"]
        assert written == [upstreams / "proggest-es" / "backend.servers"]

    def test_a_dry_run_writes_nothing(self, upstreams: Path) -> None:
        set_fs(DryRunFileSystem())

        webserver.write_servers("proggest-es", "backend", [3001])

        assert not upstreams.exists()

    def test_a_write_that_fails_leaves_the_previous_file_and_no_temporary_one(
        self, upstreams: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        webserver.write_servers("proggest-es", "backend", [3001])

        def refuse(source: Any, destination: Any) -> None:
            raise OSError("disk full")

        # A context, so only this patch is undone: the fixture's redirection of
        # the upstreams directory must outlive it for the reads below.
        with monkeypatch.context() as patch:
            patch.setattr(os, "replace", refuse)
            with pytest.raises(NginxError, match="disk full"):
                webserver.write_servers("proggest-es", "backend", [3002])

        directory = upstreams / "proggest-es"
        assert [entry.name for entry in directory.iterdir()] == ["backend.servers"]
        assert webserver.read_servers("proggest-es", "backend") == [3001]

    def test_refuses_to_write_through_a_symlinked_file(
        self, upstreams: Path, tmp_path: Path
    ) -> None:
        victim = tmp_path / "victim"
        victim.write_text("keep me\n")
        directory = upstreams / "proggest-es"
        directory.mkdir(parents=True)
        (directory / "backend.servers").symlink_to(victim)

        with pytest.raises(NginxError, match="symlink"):
            webserver.write_servers("proggest-es", "backend", [3001])

        assert victim.read_text() == "keep me\n"
        assert (directory / "backend.servers").is_symlink()

    def test_refuses_to_write_through_a_symlinked_app_directory(
        self, upstreams: Path, tmp_path: Path
    ) -> None:
        elsewhere = tmp_path / "elsewhere"
        elsewhere.mkdir()
        upstreams.mkdir(parents=True)
        (upstreams / "proggest-es").symlink_to(elsewhere)

        with pytest.raises(NoustError):
            webserver.write_servers("proggest-es", "backend", [3001])

        assert list(elsewhere.iterdir()) == []

    @pytest.mark.parametrize("port", [0, -1, 65536, 99999])
    def test_refuses_a_port_out_of_range_and_writes_nothing(
        self, upstreams: Path, port: int
    ) -> None:
        webserver.write_servers("proggest-es", "backend", [3001])

        with pytest.raises(ValidationError):
            webserver.write_servers("proggest-es", "backend", [3002, port])

        assert webserver.read_servers("proggest-es", "backend") == [3001]

    @pytest.mark.parametrize("port", ["3001", 3001.0, None, True])
    def test_refuses_a_port_that_is_not_an_integer(self, upstreams: Path, port: Any) -> None:
        with pytest.raises(ValidationError):
            webserver.write_servers("proggest-es", "backend", [port])

    def test_refuses_an_empty_list_because_nginx_refuses_an_upstream_with_no_servers(
        self, upstreams: Path
    ) -> None:
        with pytest.raises(ValidationError, match="at least one"):
            webserver.write_servers("proggest-es", "backend", [])

    def test_a_hub_does_not_write_sites_infrastructure(self, upstreams: Path, hub: None) -> None:
        with pytest.raises(RoleError):
            webserver.write_servers("proggest-es", "backend", [3001])

        assert not upstreams.exists()


# ---------------------------------------------------------------------------
# read_servers
# ---------------------------------------------------------------------------


class TestReadServers:
    """Reading is the inverse of writing, and tolerant of a hand-edited file."""

    def test_a_missing_file_has_no_servers(self, upstreams: Path) -> None:
        assert webserver.read_servers("proggest-es", "backend") == []

    def test_returns_the_ports_in_file_order(self, upstreams: Path) -> None:
        webserver.write_servers("proggest-es", "backend", [3002, 3001])

        assert webserver.read_servers("proggest-es", "backend") == [3002, 3001]

    def test_ignores_comments_and_blank_lines(self, upstreams: Path) -> None:
        path = webserver.servers_file("proggest-es", "backend")
        path.parent.mkdir(parents=True)
        path.write_text(
            "# the relay\n\nserver 127.0.0.1:3001;  # holder\n  server 127.0.0.1:3002;\n"
        )

        assert webserver.read_servers("proggest-es", "backend") == [3001, 3002]

    def test_does_not_read_through_a_symlink(self, upstreams: Path, tmp_path: Path) -> None:
        secret = tmp_path / "secret"
        secret.write_text("server 127.0.0.1:9999;\n")
        path = webserver.servers_file("proggest-es", "backend")
        path.parent.mkdir(parents=True)
        path.symlink_to(secret)

        assert webserver.read_servers("proggest-es", "backend") == []


# ---------------------------------------------------------------------------
# remove_servers
# ---------------------------------------------------------------------------


class TestRemoveServers:
    """Removal leaves nothing of an app behind, and never follows a link."""

    def test_removes_one_service_file(self, upstreams: Path) -> None:
        webserver.write_servers("proggest-es", "backend", [3001])
        webserver.write_servers("proggest-es", "frontend", [3000])

        assert webserver.remove_servers("proggest-es", "backend") is True

        assert webserver.read_servers("proggest-es", "backend") == []
        assert webserver.read_servers("proggest-es", "frontend") == [3000]

    def test_removes_the_whole_app_directory_when_no_service_is_named(
        self, upstreams: Path
    ) -> None:
        webserver.write_servers("proggest-es", "backend", [3001])
        webserver.write_servers("proggest-es", "frontend", [3000])

        assert webserver.remove_servers("proggest-es") is True

        assert not (upstreams / "proggest-es").exists()

    def test_says_when_there_was_nothing_to_remove(self, upstreams: Path) -> None:
        assert webserver.remove_servers("proggest-es") is False
        assert webserver.remove_servers("proggest-es", "backend") is False

    def test_a_dry_run_removes_nothing(self, upstreams: Path) -> None:
        webserver.write_servers("proggest-es", "backend", [3001])
        set_fs(DryRunFileSystem())

        webserver.remove_servers("proggest-es")

        assert webserver.read_servers("proggest-es", "backend") == [3001]

    def test_does_not_follow_a_symlinked_app_directory(
        self, upstreams: Path, tmp_path: Path
    ) -> None:
        elsewhere = tmp_path / "elsewhere"
        elsewhere.mkdir()
        (elsewhere / "keep.txt").write_text("keep\n")
        upstreams.mkdir(parents=True)
        link = upstreams / "proggest-es"
        link.symlink_to(elsewhere)

        with pytest.raises(NoustError):
            webserver.remove_servers("proggest-es")

        assert (elsewhere / "keep.txt").read_text() == "keep\n"


# ---------------------------------------------------------------------------
# site_includes_servers
# ---------------------------------------------------------------------------


SERVERS = Path("/etc/nginx/noust-upstreams/proggest-es/backend.servers")


def site_with(include: str) -> str:
    """An operator's site that includes a servers file the way it was given."""
    return (
        "upstream nestjs_upstream {\n"
        f"    {include}\n"
        "    keepalive 64;\n"
        "}\n"
        "server {\n    listen 80;\n    server_name proggest.es;\n"
        "    location / { proxy_pass http://nestjs_upstream; }\n}\n"
    )


class TestSiteIncludesServers:
    """The check behind "activating the relay needs this line in your site"."""

    @pytest.mark.parametrize(
        "include",
        [
            f"include {SERVERS};",
            f'include "{SERVERS}";',
            f"include '{SERVERS}';",
            f"include   {SERVERS}  ;",
            f"include {SERVERS}; # the relay moves this one",
        ],
        ids=["bare", "double-quoted", "single-quoted", "spaced", "trailing-comment"],
    )
    def test_finds_the_include_inside_an_upstream(self, include: str) -> None:
        assert webserver.site_includes_servers(site_with(include), SERVERS) is True

    def test_finds_an_include_written_on_the_same_line_as_the_block(self) -> None:
        site = f"upstream backend {{ include {SERVERS}; keepalive 64; }}\n"

        assert webserver.site_includes_servers(site, SERVERS) is True

    def test_finds_an_include_outside_an_upstream_block(self) -> None:
        assert webserver.site_includes_servers(f"include {SERVERS};\n", SERVERS) is True

    def test_does_not_count_a_commented_out_include(self) -> None:
        site = site_with(f"# include {SERVERS};")

        assert webserver.site_includes_servers(site, SERVERS) is False

    def test_does_not_count_another_file(self) -> None:
        other = "/etc/nginx/noust-upstreams/proggest-es/frontend.servers"

        assert webserver.site_includes_servers(site_with(f"include {other};"), SERVERS) is False

    def test_does_not_count_a_file_that_only_starts_with_the_same_path(self) -> None:
        site = site_with(f"include {SERVERS}.bak;")

        assert webserver.site_includes_servers(site, SERVERS) is False

    def test_does_not_count_the_path_appearing_as_something_else(self) -> None:
        site = (
            site_with("server 127.0.0.1:3001;")
            + f"# see {SERVERS}\nadd_header X-Servers {SERVERS};\n"
        )

        assert webserver.site_includes_servers(site, SERVERS) is False

    def test_a_relative_include_is_relative_to_the_nginx_prefix(self) -> None:
        site = site_with("include noust-upstreams/proggest-es/backend.servers;")

        assert webserver.site_includes_servers(site, SERVERS) is True

    def test_a_glob_that_nginx_would_expand_to_the_file_counts(self) -> None:
        site = site_with("include /etc/nginx/noust-upstreams/proggest-es/*.servers;")

        assert webserver.site_includes_servers(site, SERVERS) is True

    def test_a_glob_does_not_cross_directories(self) -> None:
        site = site_with("include /etc/nginx/noust-upstreams/*.servers;")

        assert webserver.site_includes_servers(site, SERVERS) is False

    def test_an_empty_site_includes_nothing(self) -> None:
        assert webserver.site_includes_servers("", SERVERS) is False


# ---------------------------------------------------------------------------
# site_name_for and config_path
# ---------------------------------------------------------------------------


class TestSiteNameFor:
    """The file a domain's site is in: the store's name for it, or the domain."""

    def test_is_the_domain_when_the_store_knows_no_such_app(self, store: NoustStore) -> None:
        assert webserver.site_name_for("proggest.es") == "proggest.es"

    def test_is_the_domain_when_the_app_has_no_site_name(self, store: NoustStore) -> None:
        make_app(store, "proggest.es")

        assert webserver.site_name_for("proggest.es") == "proggest.es"

    def test_is_the_stored_site_name_when_there_is_one(self, store: NoustStore) -> None:
        make_app(store, "proggest.es", site_name="proggest")

        assert webserver.site_name_for("proggest.es") == "proggest"

    def test_reads_the_domain_the_way_config_path_does(self, store: NoustStore) -> None:
        make_app(store, "proggest.es", site_name="proggest")

        assert webserver.site_name_for("  Proggest.ES ") == "proggest"

    def test_falls_back_to_the_domain_when_the_store_cannot_be_read(self) -> None:
        class BrokenStore:
            def get_app(self, domain: str) -> None:
                raise StoreError("database is locked")

        assert webserver.site_name_for("proggest.es", store=BrokenStore()) == "proggest.es"  # type: ignore[arg-type]


class TestConfigPathResolvesTheSiteName:
    """``config_path`` is the one place a domain becomes a file name (rule 4)."""

    def test_a_domain_with_a_site_name_resolves_to_that_file(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        make_app(store, "proggest.es", site_name="proggest")

        path = nginx.config_path("proggest.es")

        assert path == nginx.sites_available.resolve() / "proggest"

    def test_a_domain_without_one_resolves_to_itself_as_before(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        make_app(store, "shop.example.com")

        assert nginx.config_path("shop.example.com").name == "shop.example.com"
        assert nginx.config_path("unknown.example.com").name == "unknown.example.com"

    def test_the_apache_suffix_is_added_to_the_site_name(
        self, apache: ApacheManager, store: NoustStore
    ) -> None:
        make_app(store, "proggest.es", site_name="proggest")

        assert apache.config_path("proggest.es").name == "proggest.conf"

    def test_the_enabled_link_follows_the_same_name(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        make_app(store, "proggest.es", site_name="proggest")
        nginx.sites_available.mkdir(parents=True)
        nginx.sites_enabled.mkdir(parents=True)
        (nginx.sites_available / "proggest").write_text(NOUST_SITE)

        assert nginx.site_exists("proggest.es")
        assert nginx.site_enabled("proggest.es") is False
        nginx.enable_site("proggest.es")

        assert (nginx.sites_enabled / "proggest").is_symlink()
        assert nginx.site_enabled("proggest.es") is True

    def test_reading_and_replacing_the_configuration_use_the_named_file(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        make_app(store, "proggest.es", site_name="proggest")
        nginx.sites_available.mkdir(parents=True)
        (nginx.sites_available / "proggest").write_text("server { listen 80; }\n")

        assert nginx.get_site_config("proggest.es") == "server { listen 80; }\n"
        nginx.replace_site_config("proggest.es", "server { listen 8080; }\n", validate=False)

        assert (nginx.sites_available / "proggest").read_text() == "server { listen 8080; }\n"
        assert not (nginx.sites_available / "proggest.es").exists()

    def test_served_names_and_the_operator_marker_read_the_named_file(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        make_app(store, "proggest.es", site_name="proggest")
        nginx.sites_available.mkdir(parents=True)
        (nginx.sites_available / "proggest").write_text(
            "server {\n    server_name proggest.es www.proggest.es;\n}\n"
        )

        assert nginx.served_names("proggest.es") == ["proggest.es", "www.proggest.es"]
        assert nginx.site_is_noust("proggest.es") is False

    def test_a_site_name_that_is_not_a_file_name_is_refused_not_resolved(
        self, nginx: NginxManager
    ) -> None:
        class TamperedStore:
            def get_app(self, domain: str) -> App:
                return App(domain=domain, site_name="../../etc/shadow")

        nginx.__dict__["store"] = TamperedStore()

        with pytest.raises(ValidationError, match="site name"):
            nginx.config_path("proggest.es")

    def test_the_domain_is_still_validated_first(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        with pytest.raises(DomainError):
            nginx.config_path("evil/../domain")

    def test_an_unreadable_store_leaves_a_site_where_it_always_was(
        self, nginx: NginxManager
    ) -> None:
        class BrokenStore:
            def get_app(self, domain: str) -> None:
                raise StoreError("database is locked")

        nginx.__dict__["store"] = BrokenStore()

        assert nginx.config_path("shop.example.com").name == "shop.example.com"


class TestDeletingASiteLeavesNoServersFiles:
    """The servers files belong to the app's site, as its blue/green upstream does."""

    def test_delete_site_removes_the_servers_directory_of_the_app(
        self, nginx: NginxManager, store: NoustStore, upstreams: Path
    ) -> None:
        domain = "shop.example.com"
        nginx.sites_available.mkdir(parents=True)
        (nginx.sites_available / domain).write_text(NOUST_SITE)
        webserver.write_servers(domain_to_app_name(domain), "backend", [3001])

        nginx.delete_site(domain)

        assert not (upstreams / domain_to_app_name(domain)).exists()

    def test_a_servers_directory_that_cannot_be_removed_does_not_fail_the_deletion(
        self, nginx: NginxManager, store: NoustStore, upstreams: Path, tmp_path: Path
    ) -> None:
        domain = "shop.example.com"
        nginx.sites_available.mkdir(parents=True)
        site = nginx.sites_available / domain
        site.write_text(NOUST_SITE)
        elsewhere = tmp_path / "elsewhere"
        elsewhere.mkdir()
        upstreams.mkdir(parents=True)
        (upstreams / domain_to_app_name(domain)).symlink_to(elsewhere)

        assert nginx.delete_site(domain) is True

        assert not site.exists()
        assert elsewhere.exists()

    def test_turning_blue_green_off_does_not_touch_the_servers_files(
        self, nginx: NginxManager, store: NoustStore, upstreams: Path
    ) -> None:
        domain = "shop.example.com"
        webserver.write_servers(domain_to_app_name(domain), "backend", [3001])

        nginx.remove_upstream(domain)

        assert webserver.read_servers(domain_to_app_name(domain), "backend") == [3001]


# ---------------------------------------------------------------------------
# list_all_sites
# ---------------------------------------------------------------------------


def write_site(manager: Any, name: str, text: str, *, enabled: bool = True) -> Path:
    """Put a site file in a manager's tree, enabled by a link unless asked."""
    manager.sites_available.mkdir(parents=True, exist_ok=True)
    manager.sites_enabled.mkdir(parents=True, exist_ok=True)
    path = manager.sites_available / name
    path.write_text(text)
    if enabled:
        (manager.sites_enabled / name).symlink_to(path)
    return path


def rows_by_name(rows: list[webserver.SiteRow]) -> dict[str, webserver.SiteRow]:
    """Index the rows by file name; every test here has one row per file."""
    indexed = {row.name: row for row in rows}
    assert len(indexed) == len(rows), "a file must appear once"
    return indexed


class TestListAllSites:
    """The list is the store and the directory together, never one instead of the other."""

    def test_a_hand_written_site_stays_in_the_list_once_the_store_has_a_site(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        make_app(store, "shop.example.com")
        write_site(nginx, "shop.example.com", NOUST_SITE.replace("{domain}", "shop.example.com"))
        store.create_site(
            Site(
                domain="shop.example.com",
                config_path=str(nginx.sites_available / "shop.example.com"),
            )
        )
        write_site(nginx, "blog.example.org", "server { server_name blog.example.org; }\n")

        rows = rows_by_name(webserver.list_all_sites(managers=[nginx]))

        assert set(rows) == {"shop.example.com", "blog.example.org"}
        assert rows["blog.example.org"].noust_managed is False
        assert rows["blog.example.org"].app is None
        assert rows["shop.example.com"].noust_managed is True
        assert rows["shop.example.com"].app == "shop.example.com"

    def test_an_adopted_site_named_after_the_operator_not_the_domain(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        make_app(store, "proggest.es", site_name="proggest")
        write_site(
            nginx,
            "proggest",
            "server {\n    listen 443 ssl;\n    server_name proggest.es www.proggest.es;\n"
            "    ssl_certificate /etc/ssl/p.pem;\n}\n",
        )

        (row,) = webserver.list_all_sites(managers=[nginx])

        assert row.name == "proggest"
        assert row.domain == "proggest.es"
        assert row.app == "proggest.es"
        assert row.noust_managed is False
        assert row.webserver == "nginx"
        assert row.enabled is True
        assert row.config_path == str(nginx.sites_available / "proggest")
        assert row.has_ssl is True
        assert row.server_names == ("proggest.es", "www.proggest.es")

    def test_the_marker_makes_a_site_noust_managed(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        write_site(nginx, "one.example.com", NOUST_SITE.replace("{domain}", "one.example.com"))
        write_site(nginx, "two.example.com", "# Generated by WASM\nserver { }\n")

        rows = rows_by_name(webserver.list_all_sites(managers=[nginx]))

        assert rows["one.example.com"].noust_managed is True
        assert rows["two.example.com"].noust_managed is True

    def test_a_file_with_no_store_record_is_its_own_domain(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        write_site(nginx, "blog.example.org", "server { }\n", enabled=False)

        (row,) = webserver.list_all_sites(managers=[nginx])

        assert row.domain == "blog.example.org"
        assert row.enabled is False
        assert row.app is None

    def test_a_file_that_is_not_a_domain_does_not_break_the_list(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        write_site(nginx, "old_site", "server { }\n")
        write_site(nginx, "blog.example.org", "server { }\n")

        rows = rows_by_name(webserver.list_all_sites(managers=[nginx]))

        assert set(rows) == {"old_site", "blog.example.org"}

    def test_the_distribution_default_site_is_not_listed(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        write_site(nginx, "default", "server { }\n")

        assert webserver.list_all_sites(managers=[nginx]) == []

    def test_both_web_servers_are_listed_with_the_apache_suffix_removed(
        self, nginx: NginxManager, apache: ApacheManager, store: NoustStore
    ) -> None:
        write_site(nginx, "a.example.com", "server { }\n")
        write_site(
            apache,
            "b.example.com.conf",
            "<VirtualHost *:80>\nServerName b.example.com\n</VirtualHost>\n",
        )

        rows = rows_by_name(webserver.list_all_sites(managers=[nginx, apache]))

        assert rows["a.example.com"].webserver == "nginx"
        assert rows["b.example.com"].webserver == "apache"
        assert rows["b.example.com"].server_names == ("b.example.com",)

    def test_an_app_is_only_the_owner_of_the_site_on_its_own_web_server(
        self, nginx: NginxManager, apache: ApacheManager, store: NoustStore
    ) -> None:
        make_app(store, "shop.example.com")
        write_site(nginx, "shop.example.com", "server { }\n")
        write_site(apache, "shop.example.com.conf", "<VirtualHost *:80>\n</VirtualHost>\n")

        rows = webserver.list_all_sites(managers=[nginx, apache])

        owners = {row.webserver: row.app for row in rows}
        assert owners == {"nginx": "shop.example.com", "apache": None}

    def test_a_store_record_whose_file_is_gone_is_still_listed(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        nginx.sites_available.mkdir(parents=True)
        store.create_site(
            Site(
                domain="gone.example.com",
                config_path=str(nginx.sites_available / "gone.example.com"),
                enabled=True,
                ssl_enabled=True,
            )
        )

        (row,) = webserver.list_all_sites(managers=[nginx])

        assert row.domain == "gone.example.com"
        assert row.name == "gone.example.com"
        assert row.noust_managed is False
        assert row.has_ssl is True
        assert row.server_names == ()

    def test_the_rows_come_in_a_stable_order(self, nginx: NginxManager, store: NoustStore) -> None:
        for name in ("c.example.com", "a.example.com", "b.example.com"):
            write_site(nginx, name, "server { }\n")

        rows = webserver.list_all_sites(managers=[nginx])

        assert [row.domain for row in rows] == ["a.example.com", "b.example.com", "c.example.com"]

    def test_a_server_with_no_web_server_installed_has_an_empty_list(
        self, nginx: NginxManager, store: NoustStore
    ) -> None:
        assert webserver.list_all_sites(managers=[nginx]) == []

    def test_listing_reads_the_store_it_is_given(self, nginx: NginxManager) -> None:
        class OneAppStore:
            def list_apps(self) -> list[App]:
                return [App(id=1, domain="proggest.es", site_name="proggest")]

            def list_sites(self) -> list[Site]:
                return []

        write_site(nginx, "proggest", "server { }\n")

        (row,) = webserver.list_all_sites(managers=[nginx], store=OneAppStore())  # type: ignore[arg-type]

        assert row.app == "proggest.es"

    def test_listing_is_read_only(self, nginx: NginxManager, store: NoustStore) -> None:
        recording = RecordingFileSystem()
        set_fs(recording)
        write_site(nginx, "a.example.com", "server { }\n")

        webserver.list_all_sites(managers=[nginx])

        assert recording.changes == []
        assert os.listdir(nginx.sites_available) == ["a.example.com"]
