# Copyright (c) 2024-2026 Yago Lopez Prado
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
:mod:`noust.deployers.helpers.site`: one guard over every write of an application's site.

A site without Noust's marker is the operator's. 3.1.17 made ``BaseDeployer``
keep it; Docker Compose and monorepo still replaced it, and Compose deleted it
to put TLS in. The guard is now one function every deployer writes through,
and these tests pin it on the real nginx manager over a temporary tree.
"""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path
from typing import Any

import pytest

from noust.core.fs import DryRunFileSystem
from noust.core.runner import FakeRunner
from noust.core.store import App, NoustStore
from noust.deployers.docker_compose import DockerComposeDeployer
from noust.deployers.helpers.site import (
    ServesDomains,
    certificate_names,
    remove_app_site,
    write_app_site,
    write_template_site,
)
from noust.deployers.monorepo import MonorepoDeployer
from noust.deployers.nodejs import NodeJSDeployer
from noust.managers.nginx_manager import NginxManager
from noust.managers.webserver import NGINX_BACKEND

DOMAIN = "shop.example.com"
OPERATOR_SITE = "server {\n    server_name shop.example.com;\n    access_log off;\n}\n"


class Log:
    """Records what a helper says."""

    def __init__(self) -> None:
        self.warnings: list[str] = []
        self.lines: list[str] = []

    def warning(self, message: str) -> None:
        self.warnings.append(message)

    def substep(self, message: str) -> None:
        self.lines.append(message)

    def debug(self, message: str) -> None:
        self.lines.append(message)


@pytest.fixture
def store(tmp_path: Path) -> Any:
    """A store in the test's directory, installed as the process-wide singleton."""
    NoustStore.reset_instance()
    instance = NoustStore(tmp_path / "wasm.db")
    yield instance
    NoustStore.reset_instance()


@pytest.fixture
def web(tmp_path: Path, runner: FakeRunner, store: NoustStore) -> NginxManager:
    """An nginx manager writing into a temporary configuration tree."""
    return NginxManager(
        backend=replace(
            NGINX_BACKEND,
            sites_available=tmp_path / "nginx/sites-available",
            sites_enabled=tmp_path / "nginx/sites-enabled",
        )
    )


def operator_site(web: NginxManager) -> Path:
    """Put a hand-written site for the domain in place."""
    path = web.config_path(DOMAIN)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(OPERATOR_SITE)
    return path


def test_a_text_site_is_written_and_enabled(web: NginxManager) -> None:
    log = Log()

    outcome = write_app_site(
        DOMAIN, lambda: "# Generated by Noust\nserver {}\n", logger=log, manager=web
    )

    assert outcome == "written"
    assert web.get_site_config(DOMAIN) == "# Generated by Noust\nserver {}\n"
    assert web.site_enabled(DOMAIN)


def test_a_site_noust_wrote_is_rewritten(web: NginxManager) -> None:
    write_app_site(DOMAIN, lambda: "# Generated by Noust\nold\n", logger=Log(), manager=web)

    write_app_site(DOMAIN, lambda: "# Generated by Noust\nnew\n", logger=Log(), manager=web)

    assert web.get_site_config(DOMAIN) == "# Generated by Noust\nnew\n"


def test_the_operator_site_is_kept_and_not_even_rendered(web: NginxManager) -> None:
    operator_site(web)
    log = Log()

    def render() -> str:
        raise AssertionError("an operator's site is never rendered over")

    outcome = write_app_site(DOMAIN, render, logger=log, manager=web)

    assert outcome == "kept_operator"
    assert web.get_site_config(DOMAIN) == OPERATOR_SITE
    assert any("Noust did not write" in w for w in log.warnings)


def test_a_rehearsal_writes_nothing(web: NginxManager, tmp_path: Path) -> None:
    dry = DryRunFileSystem()

    write_app_site(DOMAIN, lambda: "# Generated by Noust\n", logger=Log(), manager=web, fs=dry)

    assert not web.site_exists(DOMAIN)
    assert any("would write" in change for change in dry.skipped)
    assert any("would link" in change for change in dry.skipped)


def test_a_template_site_reads_the_aliases_from_the_store(
    web: NginxManager, store: NoustStore
) -> None:
    store.create_app(App(domain=DOMAIN, app_type="docker-compose", port=3001))
    store.add_domain(DOMAIN, "tienda.example.com", "alias")
    store.add_domain(DOMAIN, "www.shop.example.com", "redirect")

    outcome = write_template_site(
        web, DOMAIN, template="proxy", context={"port": 3001, "ssl": False}, logger=Log()
    )

    text = web.get_site_config(DOMAIN) or ""
    assert outcome == "written"
    assert "server_name shop.example.com tienda.example.com;" in text
    assert "server_name www.shop.example.com;" in text
    assert web.site_enabled(DOMAIN)


def test_a_template_never_replaces_the_operator_site_and_names_what_it_lacks(
    web: NginxManager, store: NoustStore
) -> None:
    store.create_app(App(domain=DOMAIN, app_type="docker-compose", port=3001))
    store.add_domain(DOMAIN, "tienda.example.com", "alias")
    operator_site(web)
    log = Log()

    outcome = write_template_site(web, DOMAIN, template="proxy", context={"port": 3001}, logger=log)

    assert outcome == "kept_operator"
    assert web.get_site_config(DOMAIN) == OPERATOR_SITE
    assert any("tienda.example.com" in w and "server_name" in w for w in log.warnings)


def test_removing_the_operator_site_keeps_it(web: NginxManager) -> None:
    operator_site(web)
    log = Log()

    assert remove_app_site(DOMAIN, logger=log, manager=web) == "kept_operator"
    assert web.get_site_config(DOMAIN) == OPERATOR_SITE
    assert any("noust site delete" in w for w in log.warnings)


def test_removing_a_noust_site_deletes_it_and_reloads(
    web: NginxManager, runner: FakeRunner
) -> None:
    write_app_site(DOMAIN, lambda: "# Generated by Noust\n", logger=Log(), manager=web)

    assert remove_app_site(DOMAIN, logger=Log(), manager=web) == "removed"
    assert not web.site_exists(DOMAIN)
    assert not web.site_enabled(DOMAIN)
    assert any("reload" in " ".join(call) for call in runner.calls)


def test_removing_nothing_says_so(web: NginxManager) -> None:
    assert remove_app_site(DOMAIN, logger=Log(), manager=web) == "absent"


def test_the_certificate_covers_redirects_too(store: NoustStore) -> None:
    store.create_app(App(domain=DOMAIN, app_type="docker-compose", port=3001))
    store.add_domain(DOMAIN, "tienda.example.com", "alias")
    store.add_domain(DOMAIN, "www.shop.example.com", "redirect")

    assert certificate_names(store, DOMAIN) == [
        DOMAIN,
        "tienda.example.com",
        "www.shop.example.com",
    ]


@pytest.mark.parametrize("deployer", [NodeJSDeployer, DockerComposeDeployer, MonorepoDeployer])
def test_every_proxying_deployer_serves_domains(deployer: type) -> None:
    """domains.py asks for the capability, not for BaseDeployer."""
    assert isinstance(deployer(), ServesDomains)


# -- Monorepo ------------------------------------------------------------------


def monorepo_deployed(store: NoustStore, tmp_path: Path) -> None:
    """A monorepo as a deploy leaves it: its row, a unit and a site per workspace."""
    from noust.core.store import Service, Site

    app = store.create_app(
        App(domain=DOMAIN, app_type="monorepo", app_path=str(tmp_path), port=3000)
    )
    for name, sub, port in (("web", "www", 3000), ("api", "api", 3001)):
        store.create_service(
            Service(app_id=app.id, name=f"shop-example-com-{name}", port=port, command="x")
        )
        store.create_site(
            Site(app_id=app.id, domain=f"{sub}.{DOMAIN}", proxy_port=port, webserver="nginx")
        )


def test_a_monorepo_answers_on_its_aliases_and_redirects(
    web: NginxManager, store: NoustStore, tmp_path: Path, runner: FakeRunner
) -> None:
    monorepo_deployed(store, tmp_path)
    store.add_domain(DOMAIN, "tienda.example.com", "alias")
    store.add_domain(DOMAIN, "www.tienda.example.com", "redirect")
    deployer = MonorepoDeployer(runner=runner)
    deployer.configure(DOMAIN, str(tmp_path), app_path=tmp_path)
    deployer._webserver_manager = lambda: web  # type: ignore[method-assign]

    deployer.refresh_site(with_ssl=True)

    text = web.get_site_config(DOMAIN) or ""
    assert f"server_name {DOMAIN} tienda.example.com;" in text
    assert f"www.{DOMAIN}" in text and f"api.{DOMAIN}" in text
    assert "server_name www.tienda.example.com;" in text
    assert "return 301 https://www.shop.example.com$request_uri;" in text


def test_a_monorepo_keeps_the_operator_site(
    web: NginxManager, store: NoustStore, tmp_path: Path, runner: FakeRunner
) -> None:
    monorepo_deployed(store, tmp_path)
    operator_site(web)
    deployer = MonorepoDeployer(runner=runner)
    deployer.configure(DOMAIN, str(tmp_path), app_path=tmp_path)
    deployer._webserver_manager = lambda: web  # type: ignore[method-assign]

    deployer.refresh_site(with_ssl=False)

    assert web.get_site_config(DOMAIN) == OPERATOR_SITE


def test_a_monorepo_certificate_covers_its_subdomains_and_aliases(
    store: NoustStore, tmp_path: Path, runner: FakeRunner
) -> None:
    from types import SimpleNamespace

    from noust.managers.cert_manager import CertManager

    monorepo_deployed(store, tmp_path)
    store.add_domain(DOMAIN, "tienda.example.com", "alias")
    certs = CertManager()
    certs.LETSENCRYPT_DIR = tmp_path / "letsencrypt"
    certs.LIVE_DIR = certs.LETSENCRYPT_DIR / "live"
    certs.config = SimpleNamespace(ssl_email="")  # type: ignore[assignment]
    deployer = MonorepoDeployer(runner=runner)
    deployer.configure(DOMAIN, str(tmp_path), app_path=tmp_path)
    deployer.cert_manager = certs

    deployer.obtain_certificate()

    certbot = next(call for call in runner.calls if call[:2] == ("certbot", "certonly"))
    names = {certbot[i + 1] for i, arg in enumerate(certbot) if arg == "-d"}
    assert {DOMAIN, f"www.{DOMAIN}", f"api.{DOMAIN}", "tienda.example.com"} <= names


def test_a_failed_monorepo_deploy_keeps_the_operator_site(
    web: NginxManager, store: NoustStore, tmp_path: Path, runner: FakeRunner
) -> None:
    from types import SimpleNamespace

    operator_site(web)
    deployer = MonorepoDeployer(runner=runner)
    deployer.configure(DOMAIN, str(tmp_path), app_path=tmp_path)
    deployer._webserver_manager = lambda: web  # type: ignore[method-assign]
    deployer.deploy_target = SimpleNamespace(undo_fetch=lambda fs, log: None)  # type: ignore[assignment]

    deployer._rollback()

    assert web.get_site_config(DOMAIN) == OPERATOR_SITE
