# Copyright (c) 2024-2026 Yago Lopez Prado
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
The node's side of enrollment: authorize a central, or stop trusting it.

``noust fleet authorize`` runs on the node, as root, by the node's own
operator - the central never gets a shell here. It:

1. makes sure the console runs as a service, bound to loopback only;
2. creates the unprivileged account centrals log in as, ``noust-tunnel``
   (a system account with no home, ``nologin`` as its shell and ``*`` as its
   password, so no password ever works and a locked-account check never
   refuses its key), and restricts it in sshd itself with a Noust
   ``Match User noust-tunnel`` block (:func:`tunnel_policy_block`): its keys
   are read from a root-owned file it cannot edit, it may forward a local
   port to the console and nothing else - no Unix-socket forwarding, no
   remote forwarding, no terminal, no agent, no X11, no command but
   ``/usr/bin/false``;
3. installs the central's key in that account's key file, as::

       restrict,port-forwarding,permitopen="127.0.0.1:<console port>",permitlisten="127.0.0.1:1",command="/usr/bin/false" ssh-ed25519 AAAA... noust-central:<central>

   ``restrict`` turns off everything (port, agent and X11 forwarding, pty,
   user rc); ``port-forwarding`` turns TCP forwarding back on, in both
   directions; ``permitopen`` narrows ``ssh -L`` to the console on loopback
   and ``permitlisten`` narrows TCP ``ssh -R`` to a port nothing uses (see
   :data:`NO_LISTEN`); the forced command makes any attempt to run something
   exit 1. The key's options and the ``Match`` block say the same thing
   twice on purpose: a line pasted without its options is still contained;
4. creates a ``fleet`` token, ``fleet-<central>``, and records this server's
   access ceiling for its centrals when ``--access`` is given
   (:mod:`noust.fleet.policy`);
5. prints the join code the central needs: this server's host key, the SSH
   user and port, the console port and the token.

**Why not root.** Up to 3.0 the key went into root's ``authorized_keys``,
and the claim was that it could forward one port and do nothing else. That
was not true: ``permitlisten`` only limits TCP listeners, so the same key
could ask for ``ssh -R /path/to/socket:...`` and sshd created that Unix socket
**as root**, anywhere - ``/etc/nologin`` included, which stops every non-root
login. ``noust-tunnel`` cannot create a file anywhere it could not already,
and its ``Match`` block refuses Unix-socket forwarding outright
(``AllowStreamLocalForwarding no``). ``--ssh-user root`` still works, with
an explicit ``--i-understand`` and a warning; a node authorized by 3.0 moves
with ``noust node migrate-tunnel`` on the central.

Every check runs before anything changes; each step that changes something
puts it back when a later one fails and it can be put back.

``noust fleet deauthorize`` removes the central's key lines and revokes its
tokens.
"""

from __future__ import annotations

import binascii
import errno
import fcntl
import fnmatch
import grp
import hashlib
import os
import pwd
import re
import shlex
import stat
import threading
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

from noust import __version__
from noust.core.applock import locks_directory
from noust.core.exceptions import ConfigError, NodeError, SecurityError
from noust.core.fs import FileSystem, get_fs
from noust.core.runner import CommandError, CommandRunner, get_runner
from noust.core.sealing import SealError
from noust.fleet.joincode import JoinCode
from noust.fleet.models import (
    PublicKey,
    central_name,
    local_node_name,
    parse_public_key,
    validate_central_name,
    validate_ssh_user,
)
from noust.fleet.policy import DEFAULT_ACCESS, FleetAccess, current_access, set_access

if TYPE_CHECKING:
    from noust.core.store import NoustStore
    from noust.web.auth import TokenManager

#: The server configuration read when ``sshd -T`` cannot run.
SSHD_CONFIG = Path("/etc/ssh/sshd_config")

#: The directory sshd includes configuration fragments from, on every
#: distribution that has one (Debian 11+, Ubuntu 20.04+, Fedora, RHEL 9).
SSHD_DROPIN_DIR = Path("/etc/ssh/sshd_config.d")

#: Noust's fragment there. ``00-`` so it is read before any other (Ubuntu's
#: cloud images ship ``50-cloud-init.conf``): when two ``Match`` blocks apply
#: to one account, sshd keeps the first value it reads.
SSHD_DROPIN_NAME = "00-noust-tunnel.conf"

#: Marks the block when sshd_config includes no fragment directory and the
#: block is appended to the file itself, last (a ``Match`` runs to the end).
POLICY_BEGIN = "# BEGIN Noust fleet tunnel account (generated by Noust; do not edit)"
POLICY_END = "# END Noust fleet tunnel account"

#: This server's ed25519 host key, which the join code carries.
HOST_KEY_FILE = Path("/etc/ssh/ssh_host_ed25519_key.pub")

#: The account centrals' tunnels log in as, by default.
TUNNEL_USER = "noust-tunnel"

#: Where the tunnel account's keys live: a directory and file of root's, so
#: the account can neither add a key nor leave anything for sshd to read.
TUNNEL_KEYS_DIR = Path("/etc/ssh/noust")

#: sshd reads an account's keys with that account's privileges, so the file
#: and its directory must be readable by it - and writable by root alone,
#: which StrictModes checks. Public keys only: nothing secret is in it.
TUNNEL_KEYS_MODE = 0o644
TUNNEL_KEYS_DIR_MODE = 0o755

#: The tunnel account's home. It must not exist: nothing is ever read from it.
TUNNEL_HOME = "/nonexistent"

#: Shells that let nobody in, tried in order for a new account.
NOLOGIN_SHELLS = ("/usr/sbin/nologin", "/sbin/nologin", "/usr/bin/nologin")

#: Shells an existing tunnel account may have; anything else can log in.
NO_LOGIN_SHELLS = frozenset({*NOLOGIN_SHELLS, "/bin/false", "/usr/bin/false"})

#: sshd units, as Debian/Ubuntu and RHEL/SUSE name them.
SSHD_UNITS = ("ssh.service", "sshd.service")

#: Comment of every key line this module writes: ``noust-central:<central>``.
KEY_COMMENT_PREFIX = "noust-central:"

#: What any command sent with the central's key runs instead.
FORCED_COMMAND = "/usr/bin/false"

#: How every restricted line Noust has ever written starts, 3.0's included,
#: whatever its comment says. In root's file such a line is a central's tunnel
#: key that can still make sshd create Unix sockets as root.
TUNNEL_OPTIONS_PREFIX = 'restrict,port-forwarding,permitopen="127.0.0.1:'

#: Mode of the copy of an ``authorized_keys`` file kept before a key is taken
#: out of it: it lists who may log in, which is nobody else's business.
KEYS_BACKUP_MODE = 0o600

#: Key types a line of an ``authorized_keys`` file may name, by prefix.
_KEY_TYPE = re.compile(r"(?:ssh-|ecdsa-|sk-)[A-Za-z0-9@.-]+")

#: What a key blob is made of; anything else is not spelled into a command.
_BLOB = re.compile(r"[A-Za-z0-9+/]+={0,3}")

#: The only remote forward (``ssh -R``) the central's key may ask for.
#: ``port-forwarding`` re-enables remote forwarding along with local, and a
#: remote forward on the node's loopback could impersonate its console (bind
#: the console's port while it restarts) and collect what the operator's own
#: SSH-tunnel sessions send it. OpenSSH has no ``permitlisten="none"`` - the
#: value must be ``[host:]port`` with a port above 0, and anything else makes
#: sshd reject the whole key - so the tightest value is a port nothing can
#: use: sshd refuses a listen below 1024 to every account but root, and
#: nothing on a node connects to loopback port 1 (tcpmux) even when the key
#: is root's. The host is explicit because ssh sends ``localhost`` when none
#: is given, which does not match it, so a plain ``-R 1:...`` is refused too.
#: It says nothing about Unix-socket listeners: that is what the tunnel
#: account's ``AllowStreamLocalForwarding no`` is for.
NO_LISTEN = "127.0.0.1:1"

#: How long ``sshd -T``, ``sshd -t``, ``chown``, ``useradd`` and a reload may take.
SSHD_TIMEOUT = 15

#: Mode of the ``.ssh`` directory this module creates in a home.
SSH_DIR_MODE = 0o700

#: Mode of ``authorized_keys`` in a home.
AUTHORIZED_KEYS_MODE = 0o600

#: Mode of Noust's sshd fragment: sshd reads it as root, and hardening
#: benchmarks (CIS) want sshd's configuration readable by root alone. An
#: existing sshd_config keeps the mode it has.
SSHD_POLICY_MODE = 0o600

#: Mode of the lock file :func:`_locked_for_write` takes.
LOCK_FILE_MODE = 0o600

#: The fleet token scope. Spelled here because this module must import
#: without the console's dependencies; ``noust.web.auth.FLEET_SCOPE``.
FLEET_SCOPE = "fleet"

#: Shown as the token in a dry-run join code. Shaped like a real fleet token
#: (``noust.web.auth.API_TOKEN_PREFIX``, spelled here for the same reason
#: FLEET_SCOPE is) so it round-trips through :class:`~noust.fleet.joincode.JoinCode`,
#: but it is never minted or stored, so nothing accepts it: pasting it into
#: ``noust node add`` fails as a bad token, not a bad join code.
DRY_RUN_TOKEN = "noust_tok_dry-run-token-was-not-issued"  # noqa: S105 - a placeholder, never issued

#: What ``sshd -T -C`` is told about the connection it evaluates. Only the
#: account matters to Noust's ``Match User`` block; the central's own address
#: is not known here.
EVALUATE_HOST = "localhost"
EVALUATE_ADDR = "127.0.0.1"

#: A progress callback: the step being started, how many there are, and what it does.
Progress = Callable[[int, int, str], None]


@dataclass(frozen=True)
class SshdSettings:
    """
    The parts of sshd's configuration enrollment depends on.

    Read with ``sshd -T -C user=<account>,...`` they are what sshd applies to
    that account, ``Match`` blocks included; read from the file (sshd
    missing) they are the global section only.

    Attributes:
        port: The first port sshd listens on.
        allow_tcp_forwarding: ``yes``, ``all``, ``local``, ``remote`` or ``no``.
        disable_forwarding: Whether ``DisableForwarding`` turns every kind off.
        permit_root_login: ``PermitRootLogin``.
        authorized_keys_files: ``AuthorizedKeysFile``, unexpanded.
        source: ``sshd -T``, the config file, or ``defaults``.
        allow_stream_local_forwarding: ``AllowStreamLocalForwarding``.
        permit_open: ``PermitOpen`` entries (``any`` when unrestricted).
        permit_tty: ``PermitTTY``.
        x11_forwarding: ``X11Forwarding``.
        allow_agent_forwarding: ``AllowAgentForwarding``.
        force_command: ``ForceCommand``, None when there is none.
        allow_users: ``AllowUsers`` patterns.
        deny_users: ``DenyUsers`` patterns.
        allow_groups: ``AllowGroups`` patterns.
        deny_groups: ``DenyGroups`` patterns.
    """

    port: int = 22
    allow_tcp_forwarding: str = "yes"
    disable_forwarding: bool = False
    permit_root_login: str = "prohibit-password"
    authorized_keys_files: tuple[str, ...] = (".ssh/authorized_keys", ".ssh/authorized_keys2")
    source: str = "defaults"
    allow_stream_local_forwarding: str = "yes"
    permit_open: tuple[str, ...] = ("any",)
    permit_tty: str = "yes"
    x11_forwarding: str = "no"
    allow_agent_forwarding: str = "yes"
    force_command: str | None = None
    allow_users: tuple[str, ...] = ()
    deny_users: tuple[str, ...] = ()
    allow_groups: tuple[str, ...] = ()
    deny_groups: tuple[str, ...] = ()


#: Keywords that may repeat and accumulate: ``sshd -T`` prints one line per
#: entry, and a config file may spread them over several lines.
_ACCUMULATED = ("allowusers", "denyusers", "allowgroups", "denygroups")


def _parse_sshd(lines: list[str], source: str) -> SshdSettings:
    """
    Read sshd settings from ``sshd -T`` output or ``sshd_config`` lines.

    The first value of each keyword wins, as in sshd, except for the access
    lists, which accumulate; a ``Match`` block ends what applies to everyone.

    Args:
        lines: The lines.
        source: Where they came from.

    Returns:
        The settings, defaults for what is not named.
    """
    found: dict[str, str] = {}
    lists: dict[str, list[str]] = {name: [] for name in _ACCUMULATED}
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        keyword, _, value = line.partition(" ")
        if "=" in keyword:
            keyword, _, value = line.partition("=")
        keyword = keyword.strip().lower()
        if keyword == "match":
            break
        if keyword in lists:
            lists[keyword].extend(value.split())
            continue
        found.setdefault(keyword, value.strip())
    defaults = SshdSettings()
    port_text = found.get("port", "").split()[0] if found.get("port") else ""
    files = tuple(found["authorizedkeysfile"].split()) if found.get("authorizedkeysfile") else ()
    force = found.get("forcecommand")
    return SshdSettings(
        port=int(port_text)
        if port_text.isdigit() and 0 < int(port_text) < 65536
        else defaults.port,
        allow_tcp_forwarding=found.get("allowtcpforwarding", defaults.allow_tcp_forwarding).lower(),
        disable_forwarding=found.get("disableforwarding", "no").lower() == "yes",
        permit_root_login=found.get("permitrootlogin", defaults.permit_root_login).lower(),
        authorized_keys_files=files or defaults.authorized_keys_files,
        source=source,
        allow_stream_local_forwarding=found.get(
            "allowstreamlocalforwarding", defaults.allow_stream_local_forwarding
        ).lower(),
        permit_open=tuple(found["permitopen"].split())
        if found.get("permitopen")
        else defaults.permit_open,
        permit_tty=found.get("permittty", defaults.permit_tty).lower(),
        x11_forwarding=found.get("x11forwarding", defaults.x11_forwarding).lower(),
        allow_agent_forwarding=found.get(
            "allowagentforwarding", defaults.allow_agent_forwarding
        ).lower(),
        force_command=None if force is None or force.lower() == "none" else force,
        allow_users=tuple(lists["allowusers"]),
        deny_users=tuple(lists["denyusers"]),
        allow_groups=tuple(lists["allowgroups"]),
        deny_groups=tuple(lists["denygroups"]),
    )


def read_sshd_settings(
    runner: CommandRunner | None = None,
    config_path: Path = SSHD_CONFIG,
    *,
    user: str | None = None,
) -> SshdSettings:
    """
    Learn sshd's effective settings: ``sshd -T``, else its config file, else defaults.

    Args:
        runner: The runner ``sshd -T`` goes through.
        config_path: The file read when ``sshd -T`` cannot run.
        user: Evaluate for this account (``sshd -T -C user=...``), so the
            ``Match`` blocks that apply to it count - which is where Noust's
            own restrictions on the tunnel account live, and where an
            ``AllowUsers`` elsewhere would shut it out. None reads the global
            section only.

    Returns:
        The settings.
    """
    argv = ["sshd", "-T"]
    if user is not None:
        argv += [
            "-C",
            f"user={validate_ssh_user(user)},host={EVALUATE_HOST},addr={EVALUATE_ADDR}",
        ]
    result = (runner or get_runner()).run(argv, timeout=SSHD_TIMEOUT)
    if result.success and result.stdout.strip():
        return _parse_sshd(result.stdout.splitlines(), " ".join(argv[:3]))
    try:
        text = config_path.read_text(encoding="utf-8")
    except OSError:
        return SshdSettings()
    return _parse_sshd(text.splitlines(), str(config_path))


def _matches(name: str, patterns: tuple[str, ...]) -> bool:
    """
    Report whether a name matches any sshd access-list pattern.

    Args:
        name: An account or group name.
        patterns: ``AllowUsers``-style patterns (``*`` and ``?``; a
            ``user@host`` entry is compared on its user part).

    Returns:
        True when one matches.
    """
    return any(
        fnmatch.fnmatchcase(name, pattern.partition("@")[0]) for pattern in patterns if pattern
    )


def sshd_blockers(
    settings: SshdSettings, user: str, groups: tuple[str, ...] = (), *, tunnel: bool = False
) -> list[str]:
    """
    List what in sshd's configuration would stop the central's tunnel.

    Args:
        settings: sshd's settings for the account (``-C``).
        user: The account the key is installed for.
        groups: The account's groups, for ``AllowGroups``/``DenyGroups``.
        tunnel: The account is Noust's tunnel account: forwarding is its own
            ``Match`` block's to allow, so a global ban is not a blocker.

    Returns:
        One actionable sentence per problem.
    """
    blockers: list[str] = []
    if not tunnel and (
        settings.disable_forwarding or settings.allow_tcp_forwarding in ("no", "remote")
    ):
        blockers.append(
            "sshd does not allow local TCP forwarding (AllowTcpForwarding or "
            "DisableForwarding), which is all the central's key may do. Set "
            "'AllowTcpForwarding local' (or yes) in /etc/ssh/sshd_config, reload sshd, "
            "and authorize again."
        )
    if user == "root" and settings.permit_root_login == "no":
        blockers.append(
            "sshd refuses root logins (PermitRootLogin no). Authorize for the tunnel "
            f"account instead (drop --ssh-user root: {TUNNEL_USER} is the default), or "
            "allow key logins for root (PermitRootLogin prohibit-password)."
        )
    reload_hint = "reload sshd (systemctl reload ssh, or sshd) and authorize again."
    if settings.allow_users and not _matches(user, settings.allow_users):
        blockers.append(
            f"sshd only lets these accounts in (AllowUsers {' '.join(settings.allow_users)}), "
            f"and {user} is not one of them. Add {user} to AllowUsers, then {reload_hint}"
        )
    if _matches(user, settings.deny_users):
        blockers.append(
            f"sshd refuses {user} (DenyUsers {' '.join(settings.deny_users)}). "
            f"Remove it from DenyUsers, then {reload_hint}"
        )
    if settings.allow_groups and not any(_matches(g, settings.allow_groups) for g in groups):
        blockers.append(
            f"sshd only lets members of these groups in (AllowGroups "
            f"{' '.join(settings.allow_groups)}), and {user} is in none of them "
            f"({', '.join(groups) or 'no group'}). Add one of its groups to AllowGroups, "
            f"then {reload_hint}"
        )
    if any(_matches(g, settings.deny_groups) for g in groups):
        blockers.append(
            f"sshd refuses a group {user} is in (DenyGroups {' '.join(settings.deny_groups)}). "
            f"Remove it from DenyGroups, then {reload_hint}"
        )
    return blockers


def authorized_keys_path(settings: SshdSettings, account: pwd.struct_passwd) -> Path:
    """
    Find the ``authorized_keys`` file sshd reads for an account.

    Args:
        settings: sshd's settings.
        account: The account.

    Returns:
        The first ``AuthorizedKeysFile`` entry, expanded; relative entries
        are under the account's home.

    Raises:
        NodeError: When sshd reads no authorized_keys file at all.
    """
    for entry in settings.authorized_keys_files:
        if entry.lower() == "none":
            continue
        expanded = (
            entry.replace("%%", "\x00")
            .replace("%h", account.pw_dir)
            .replace("%u", account.pw_name)
            .replace("%U", str(account.pw_uid))
            .replace("\x00", "%")
        )
        path = Path(expanded)
        return path if path.is_absolute() else Path(account.pw_dir) / path
    raise NodeError(
        "sshd reads no authorized_keys file (AuthorizedKeysFile none)",
        details="Set AuthorizedKeysFile in /etc/ssh/sshd_config, reload sshd, and authorize again.",
    )


def key_comment(central: str) -> str:
    """
    The comment that marks a central's line in ``authorized_keys``.

    Args:
        central: The central's name.

    Returns:
        ``noust-central:<central>``.
    """
    return f"{KEY_COMMENT_PREFIX}{validate_central_name(central)}"


def authorized_key_line(central: str, key: PublicKey, console_port: int) -> str:
    """
    Spell the central's restricted ``authorized_keys`` line.

    Args:
        central: The central's name.
        key: The central's public key for this node.
        console_port: The console's loopback port, the only one it may reach.

    Returns:
        The line, without a newline.
    """
    options = (
        f'restrict,port-forwarding,permitopen="127.0.0.1:{int(console_port)}",'
        f'permitlisten="{NO_LISTEN}",command="{FORCED_COMMAND}"'
    )
    return f"{options} {key.bare} {key_comment(central)}"


def _is_line_of(line: str, central: str) -> bool:
    """
    Report whether an ``authorized_keys`` line is a given central's.

    Args:
        line: The line.
        central: The central's name.

    Returns:
        True when its last field is the central's comment.
    """
    fields = line.split()
    return bool(fields) and fields[-1] == key_comment(central)


def key_of_line(line: str) -> tuple[str, str] | None:
    """
    Find the key an ``authorized_keys`` line holds, whatever its options and comment.

    Args:
        line: The line.

    Returns:
        ``(type, blob)``, or None for a blank line, a comment or no key.
    """
    fields = line.split()
    if not fields or fields[0].startswith("#"):
        return None
    for index, candidate in enumerate(fields[:-1]):
        if _KEY_TYPE.fullmatch(candidate):
            return candidate, fields[index + 1]
    return None


def has_tunnel_options(line: str) -> bool:
    """
    Report whether a line carries the options Noust gives a central's tunnel key.

    Args:
        line: An ``authorized_keys`` line.

    Returns:
        True when it starts with :data:`TUNNEL_OPTIONS_PREFIX`.
    """
    return line.lstrip().startswith(TUNNEL_OPTIONS_PREFIX)


def key_removal_command(path: Path | str, blob: str) -> str | None:
    """
    Spell the command that removes one key's lines from an ``authorized_keys`` file.

    Args:
        path: The file.
        blob: The key's base64 blob.

    Returns:
        ``sed -i '\\#<blob>#d' <path>``: a blob holds no ``#`` and nothing a
        basic regular expression reads as special, so it matches exactly the
        lines of that key. None when the blob is not base64.
    """
    if not _BLOB.fullmatch(blob):
        return None
    return f"sed -i '\\#{blob}#d' {shlex.quote(str(path))}"


@dataclass(frozen=True)
class RootTunnelKey:
    """
    A central's tunnel key found in root's ``authorized_keys``.

    Attributes:
        path: The file.
        line_number: Where it is, from 1.
        key_type: ``ssh-ed25519``.
        blob: The base64 key.
        comment: The line's last field when it is not the key: who it names.
    """

    path: Path
    line_number: int
    key_type: str
    blob: str
    comment: str

    @property
    def fingerprint(self) -> str:
        """``SHA256:...``; ``unknown`` for a blob that is not base64."""
        try:
            return PublicKey(self.key_type, self.blob).fingerprint
        except (binascii.Error, ValueError):
            return "unknown"

    def warning(self) -> str:
        """
        Say what the line is, why it matters and exactly how to remove it.

        Returns:
            One sentence and the command.
        """
        remove = key_removal_command(self.path, self.blob) or (
            f"delete line {self.line_number} of {self.path}"
        )
        named = f" ({self.comment})" if self.comment else ""
        return (
            f"root's {self.path} still holds a central's tunnel key{named}, "
            f"{self.fingerprint}, on line {self.line_number}: whatever its options, a key "
            "of root's can make sshd create a Unix socket as root anywhere. If no central "
            f"tunnels in as root any more, remove it: {remove} (or pass --replace-root-key "
            "with that key to 'noust fleet authorize')."
        )


def root_tunnel_keys(path: Path, text: str | None) -> list[RootTunnelKey]:
    """
    List the lines of root's ``authorized_keys`` that are a central's tunnel key.

    Args:
        path: The file.
        text: Its content, None when it does not exist.

    Returns:
        Every line carrying :data:`TUNNEL_OPTIONS_PREFIX`, in file order.
    """
    found: list[RootTunnelKey] = []
    for number, line in enumerate((text or "").splitlines(), start=1):
        key = key_of_line(line)
        if key is None or not has_tunnel_options(line):
            continue
        fields = line.split()
        comment = fields[-1] if fields[-1] != key[1] else ""
        found.append(RootTunnelKey(path, number, key[0], key[1], comment))
    return found


#: Lock paths this thread already holds, and how many nested acquisitions are
#: inside each: flock() locks belong to the open file description, not the
#: process, so a second open()+flock() of the same file on the same thread
#: would block on itself. Reentrancy lets 'authorize' hold the lock across
#: reading the file, installing the new line and - if issuing the token
#: fails - writing the previous content back, while 'install' taking it
#: again for its own read-modify-write does not deadlock.
_local = threading.local()


def _held_locks() -> dict[Path, int]:
    """
    Return the authorized_keys locks this thread already holds.

    Returns:
        Lock path to nesting depth.
    """
    held: dict[Path, int] | None = getattr(_local, "held", None)
    if held is None:
        held = {}
        _local.held = held
    return held


@contextmanager
def _locked_for_write(path: Path) -> Iterator[None]:
    """
    Hold an exclusive lock across a read-modify-write cycle on an authorized_keys file.

    ``noust fleet authorize`` for one central and ``deauthorize`` for another,
    run at the same time for the same account, both read the file before
    either writes it; without a lock the second write clobbers the first, and
    whichever central's line was added or removed second is the only change
    that survives. The lock file lives under the Noust state directory
    (:func:`~noust.core.applock.locks_directory`, next to the store's own
    per-application locks) rather than beside ``authorized_keys`` itself,
    since that directory does not always exist yet, and when it is outside
    the account's home this class does not always own it - one lock file per
    distinct target path, named by its hash, so a different account's file
    never contends with this one.

    Args:
        path: The ``authorized_keys`` file about to be read and written.

    Yields:
        Nothing; the lock is held until the block exits.
    """
    held = _held_locks()
    if path in held:
        held[path] += 1
        try:
            yield
        finally:
            held[path] -= 1
        return

    directory = locks_directory()
    try:
        get_fs().make_dir(directory, mode=0o700, parents=True)
    except FileExistsError:
        # Another authorize for another central created it in the meantime:
        # the directory is there, which is all this needs.
        pass
    digest = hashlib.sha256(str(path).encode("utf-8")).hexdigest()[:16]
    lock_path = directory / f"authorized-keys-{digest}.lock"
    # O_NOFOLLOW: the directory is root's, but a link planted there must not
    # turn "take a lock" into a write somewhere else.
    descriptor = os.open(
        lock_path, os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW | os.O_CLOEXEC, LOCK_FILE_MODE
    )
    held[path] = 1
    try:
        fcntl.flock(descriptor, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(descriptor, fcntl.LOCK_UN)
    finally:
        del held[path]
        os.close(descriptor)


def _read_no_follow(path: Path) -> str | None:
    """
    Read a file that must not be a symlink.

    ``authorized_keys`` is in a directory its user owns; a link there to
    ``/etc/shadow`` would otherwise be rewritten by root.

    Args:
        path: The file.

    Returns:
        Its text, or None when it does not exist.

    Raises:
        NodeError: When it is a symlink or cannot be read.
    """
    try:
        descriptor = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
    except FileNotFoundError:
        return None
    except OSError as exc:
        if exc.errno == errno.ELOOP:
            raise NodeError(
                f"Refusing to write through the symlink {path}",
                details="Replace it with a regular file, then authorize again.",
            ) from exc
        raise NodeError(f"Cannot read {path}", details=exc.strerror or str(exc)) from exc
    with os.fdopen(descriptor, encoding="utf-8") as handle:
        return handle.read()


class AuthorizedKeys:
    """
    Edit one account's ``authorized_keys`` through the filesystem seam.

    Args:
        path: The file.
        owner: ``(uid, gid)`` the file and a created ``.ssh`` belong to, or
            None to leave them root's (a file outside the account's home).
        fs: The filesystem seam.
        runner: The runner ``chown`` goes through.
        mode: The file's mode: 0600 in a home, 0644 for the tunnel
            account's root-owned file, which sshd reads as that account.
        dir_mode: Mode of the directory when this creates it.
    """

    def __init__(
        self,
        path: Path,
        owner: tuple[int, int] | None,
        *,
        fs: FileSystem | None = None,
        runner: CommandRunner | None = None,
        mode: int = AUTHORIZED_KEYS_MODE,
        dir_mode: int = SSH_DIR_MODE,
    ) -> None:
        self.path = path
        self.owner = owner
        self.mode = mode
        self.dir_mode = dir_mode
        self._fs = fs
        self._runner = runner

    @property
    def fs(self) -> FileSystem:
        """The filesystem seam."""
        return self._fs or get_fs()

    @property
    def runner(self) -> CommandRunner:
        """The runner chown goes through."""
        return self._runner or get_runner()

    def read(self) -> str | None:
        """
        Read the file.

        Returns:
            Its text, or None when it does not exist.

        Raises:
            NodeError: When it, or its directory, is a symlink.
        """
        if self.path.parent.is_symlink():
            raise NodeError(
                f"Refusing to write through the symlink {self.path.parent}",
                details="Replace it with a real directory, then authorize again.",
            )
        return _read_no_follow(self.path)

    def _chown(self, path: Path) -> None:
        """
        Give a path to the account, without following a link.

        Args:
            path: The file or directory.

        Raises:
            NodeError: When chown fails.
        """
        if self.owner is None or self.owner[0] == 0:
            return
        uid, gid = self.owner
        try:
            self.runner.run(
                ["chown", "-h", f"{uid}:{gid}", str(path)], timeout=SSHD_TIMEOUT, check=True
            )
        except CommandError as exc:
            raise NodeError(f"Could not give {path} to its user", details=exc.details) from exc

    def write(self, text: str | None) -> None:
        """
        Replace the file's content atomically, with its mode, owned by the account.

        Args:
            text: The new content, or None to remove the file.
        """
        if text is None:
            self.fs.remove(self.path, missing_ok=True)
            return
        directory = self.path.parent
        if not directory.exists():
            self.fs.make_dir(directory, mode=self.dir_mode, parents=True)
            # make_dir's mode passes through the umask; sshd needs exactly this.
            self.fs.chmod(directory, self.dir_mode)
            self._chown(directory)
        self.fs.write_text(self.path, text, mode=self.mode)
        if self.mode != AUTHORIZED_KEYS_MODE:
            # Likewise: a 0644 file created under umask 077 is 0600, which the
            # tunnel account could not read.
            self.fs.chmod(self.path, self.mode)
        self._chown(self.path)

    def would_change(self, line: str, central: str) -> bool:
        """
        Report whether :meth:`install` would change the file, without changing it.

        Args:
            line: :func:`authorized_key_line`'s output.
            central: The central's name.

        Returns:
            True when the file holds anything other than exactly this line
            for this central.
        """
        existing = self.read()
        lines = existing.splitlines() if existing else []
        ours = [candidate for candidate in lines if _is_line_of(candidate, central)]
        return ours != [line]

    def install(self, line: str, central: str) -> bool:
        """
        Make ``line`` the one line of ``central`` in the file.

        Any older line of the same central (another key, another port) is
        replaced; every other line is kept exactly as it was.

        Args:
            line: :func:`authorized_key_line`'s output.
            central: The central's name.

        Returns:
            True when the file changed; False when it already held exactly this.
        """
        with _locked_for_write(self.path):
            if not self.would_change(line, central):
                return False
            existing = self.read()
            lines = existing.splitlines() if existing else []
            kept = [candidate for candidate in lines if not _is_line_of(candidate, central)]
            self.write("\n".join([*kept, line]) + "\n")
            return True

    def holds_key(self, key: PublicKey) -> bool:
        """
        Report whether any line of the file holds a key, whatever its options and comment.

        Args:
            key: The key.

        Returns:
            True when one does.
        """
        existing = self.read()
        wanted = (key.key_type, key.blob)
        return any(key_of_line(line) == wanted for line in (existing or "").splitlines())

    def remove_key(self, key: PublicKey) -> Path | None:
        """
        Remove every line holding a key, keeping a copy of the file as it was.

        Matched by the key alone: a line 3.0 wrote names its central in a
        comment that need not be the name it is authorized under now.

        Args:
            key: The key.

        Returns:
            The copy (0600, next to the file, named with the UTC time), or
            None when no line held the key and nothing changed.
        """
        with _locked_for_write(self.path):
            existing = self.read()
            if not existing:
                return None
            lines = existing.splitlines()
            wanted = (key.key_type, key.blob)
            kept = [line for line in lines if key_of_line(line) != wanted]
            if len(kept) == len(lines):
                return None
            backup = self._backup_path()
            self.fs.write_text(backup, existing, mode=KEYS_BACKUP_MODE)
            self.fs.chmod(backup, KEYS_BACKUP_MODE)
            self.write("\n".join(kept) + "\n" if kept else "")
            return backup

    def _backup_path(self) -> Path:
        """
        Name a copy of the file that does not exist yet.

        Returns:
            ``<file>.noust-<UTC time>``, with a number after it when that is taken.
        """
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        candidate = self.path.with_name(f"{self.path.name}.noust-{stamp}")
        number = 1
        while os.path.lexists(candidate):
            number += 1
            candidate = self.path.with_name(f"{self.path.name}.noust-{stamp}.{number}")
        return candidate

    def lines_of(self, central: str) -> list[str]:
        """
        List the file's existing lines that belong to a central, without changing anything.

        Args:
            central: The central's name.

        Returns:
            The matching lines, in file order.
        """
        existing = self.read()
        if not existing:
            return []
        return [candidate for candidate in existing.splitlines() if _is_line_of(candidate, central)]

    def remove(self, central: str) -> int:
        """
        Remove every line of a central.

        Args:
            central: The central's name.

        Returns:
            How many lines were removed.
        """
        with _locked_for_write(self.path):
            existing = self.read()
            if not existing:
                return 0
            lines = existing.splitlines()
            kept = [candidate for candidate in lines if not _is_line_of(candidate, central)]
            removed = len(lines) - len(kept)
            if removed:
                self.write("\n".join(kept) + "\n" if kept else "")
            return removed


def _account(user: str, passwd: Callable[[str], pwd.struct_passwd]) -> pwd.struct_passwd:
    """
    Look up the SSH user.

    Args:
        user: The account name.
        passwd: ``pwd.getpwnam``.

    Returns:
        The account.

    Raises:
        NodeError: When there is no such account.
    """
    try:
        return passwd(validate_ssh_user(user))
    except KeyError as exc:
        raise NodeError(
            f"There is no account named {user} on this server",
            details="Pass --ssh-user with an account that can log in over SSH.",
        ) from exc


def _groups_of(account: pwd.struct_passwd) -> tuple[str, ...]:
    """
    Name an account's groups, primary first, for ``AllowGroups``.

    Args:
        account: The account.

    Returns:
        The group names this server knows.
    """
    names: list[str] = []
    try:
        names.append(grp.getgrgid(account.pw_gid).gr_name)
    except KeyError:
        pass
    names += [group.gr_name for group in grp.getgrall() if account.pw_name in group.gr_mem]
    return tuple(dict.fromkeys(names))


def _authorized_keys_for(
    account: pwd.struct_passwd,
    settings: SshdSettings,
    fs: FileSystem | None,
    runner: CommandRunner | None,
) -> AuthorizedKeys:
    """
    Build the editor of an account's ``authorized_keys``.

    Args:
        account: The account.
        settings: sshd's settings.
        fs: The filesystem seam.
        runner: The runner.

    Returns:
        The editor; the file belongs to the account when it is in its home.
    """
    path = authorized_keys_path(settings, account)
    home = Path(account.pw_dir)
    owned = home in path.parents
    return AuthorizedKeys(
        path, (account.pw_uid, account.pw_gid) if owned else None, fs=fs, runner=runner
    )


def tunnel_keys_file(
    user: str,
    *,
    keys_dir: Path = TUNNEL_KEYS_DIR,
    fs: FileSystem | None = None,
    runner: CommandRunner | None = None,
) -> AuthorizedKeys:
    """
    Build the editor of the tunnel account's key file: root's, readable by sshd as the account.

    Args:
        user: The tunnel account.
        keys_dir: Where the key files are.
        fs: The filesystem seam.
        runner: The runner.

    Returns:
        The editor of ``<keys_dir>/<user>.keys``.
    """
    return AuthorizedKeys(
        keys_dir / f"{validate_ssh_user(user)}.keys",
        None,
        fs=fs,
        runner=runner,
        mode=TUNNEL_KEYS_MODE,
        dir_mode=TUNNEL_KEYS_DIR_MODE,
    )


# ---------------------------------------------------------------------------
# The tunnel account
# ---------------------------------------------------------------------------


def _nologin_shell() -> str:
    """
    Pick the shell a new tunnel account gets.

    Returns:
        The first ``nologin`` this server has; ``/usr/sbin/nologin`` when
        none is found (useradd records it either way; sshd then refuses a
        session, which is all a tunnel account needs).
    """
    for candidate in NOLOGIN_SHELLS:
        if Path(candidate).exists():
            return candidate
    return NOLOGIN_SHELLS[0]


def _refuse_login_shell(account: pwd.struct_passwd) -> None:
    """
    Refuse a tunnel account someone can log in to.

    Args:
        account: The existing account.

    Raises:
        NodeError: When its shell is not one that lets nobody in.
    """
    if account.pw_shell in NO_LOGIN_SHELLS:
        return
    user = account.pw_name
    raise NodeError(
        f"The account {user} exists and can log in (its shell is {account.pw_shell})",
        details=(
            f"{user} is meant for centrals' tunnels alone. Give it a shell that lets "
            f"nobody in (usermod --shell /usr/sbin/nologin {user}) if it is yours to "
            "change, or authorize for another dedicated account with --ssh-user."
        ),
    )


def ensure_tunnel_account(
    user: str,
    *,
    runner: CommandRunner,
    passwd: Callable[[str], pwd.struct_passwd],
    dry_run: bool,
) -> tuple[pwd.struct_passwd, bool]:
    """
    Create the tunnel account, or check the one that exists.

    A system account with its own group, no home (``/nonexistent``) and a
    shell that lets nobody in. Its password field is set to ``*`` every time:
    no password matches it, and unlike the ``!`` useradd leaves, sshd never
    reads it as a locked account and refuses the key (``UsePAM no``).

    Args:
        user: The account's name.
        runner: The runner ``useradd``/``usermod`` go through.
        passwd: Account lookup.
        dry_run: Rehearse: an account that would be created is described,
            not looked up.

    Returns:
        The account, and whether it was created now.

    Raises:
        NodeError: When an account of that name exists and can log in, or
            the account cannot be created.
    """
    user = validate_ssh_user(user)
    created = False
    try:
        account: pwd.struct_passwd | None = passwd(user)
    except KeyError:
        account = None
    if account is not None:
        _refuse_login_shell(account)
    try:
        if account is None:
            runner.run(
                [
                    "useradd",
                    "--system",
                    "--user-group",
                    "--no-create-home",
                    "--home-dir",
                    TUNNEL_HOME,
                    "--shell",
                    _nologin_shell(),
                    "--comment",
                    "Noust fleet tunnel",
                    user,
                ],
                timeout=SSHD_TIMEOUT,
                check=True,
            )
            created = True
        runner.run(["usermod", "--password", "*", user], timeout=SSHD_TIMEOUT, check=True)
    except CommandError as exc:
        raise NodeError(
            f"Could not prepare the tunnel account {user}",
            details="useradd and usermod (shadow-utils) must be installed; run as root.",
            output=exc.details,
        ) from exc
    if account is None:
        try:
            account = passwd(user)
        except KeyError as exc:
            if not dry_run:
                raise NodeError(
                    f"The account {user} was not found after it was created",
                    details="Check /etc/passwd and the output of 'getent passwd "
                    f"{user}', then authorize again.",
                ) from exc
            account = pwd.struct_passwd((user, "*", 0, 0, "", TUNNEL_HOME, _nologin_shell()))
    return account, created


# ---------------------------------------------------------------------------
# The tunnel account's restrictions in sshd
# ---------------------------------------------------------------------------


def tunnel_policy_block(user: str, console_port: int, keys_dir: Path = TUNNEL_KEYS_DIR) -> str:
    """
    Spell the ``Match User`` block that restricts the tunnel account in sshd itself.

    Args:
        user: The tunnel account.
        console_port: The console's loopback port, the only place it may reach.
        keys_dir: Where its key file is.

    Returns:
        The block, ending with a newline.
    """
    lines = [
        f"Match User {validate_ssh_user(user)}",
        f"    AuthorizedKeysFile {keys_dir}/%u.keys",
        "    PubkeyAuthentication yes",
        "    AuthenticationMethods publickey",
        "    DisableForwarding no",
        "    AllowTcpForwarding local",
        "    AllowStreamLocalForwarding no",
        f"    PermitOpen 127.0.0.1:{int(console_port)}",
        "    PermitListen none",
        "    GatewayPorts no",
        "    PermitTunnel no",
        "    PermitTTY no",
        "    X11Forwarding no",
        "    AllowAgentForwarding no",
        "    PermitUserRC no",
        f"    ForceCommand {FORCED_COMMAND}",
    ]
    return "\n".join(lines) + "\n"


def _includes(sshd_config: Path, dropin: Path) -> bool:
    """
    Report whether sshd_config includes a fragment at this path.

    Args:
        sshd_config: The main configuration file.
        dropin: The fragment.

    Returns:
        True when an ``Include`` pattern names it.
    """
    try:
        text = sshd_config.read_text(encoding="utf-8")
    except OSError:
        return False
    for raw in text.splitlines():
        fields = raw.strip().split()
        if not fields or fields[0].lower() != "include":
            continue
        for pattern in fields[1:]:
            absolute = pattern if pattern.startswith("/") else str(sshd_config.parent / pattern)
            if fnmatch.fnmatchcase(str(dropin), absolute):
                return True
    return False


def _without_block(text: str) -> str:
    """
    Remove Noust's marked block from sshd_config's text.

    Args:
        text: The file's content.

    Returns:
        The content without the block, ending with a newline when not empty.
    """
    kept: list[str] = []
    inside = False
    for line in text.splitlines():
        if line.strip() == POLICY_BEGIN:
            inside = True
            continue
        if inside and line.strip() == POLICY_END:
            inside = False
            continue
        if not inside:
            kept.append(line)
    while kept and not kept[-1].strip():
        kept.pop()
    return "\n".join(kept) + "\n" if kept else ""


@dataclass
class SshdPolicy:
    """
    Where the tunnel account's restrictions are written, and what was there before.

    Attributes:
        path: The fragment, or sshd_config itself when it includes none.
        previous: The file's content before, None when it did not exist.
        content: The content it gets.
    """

    path: Path
    previous: str | None
    content: str

    @property
    def changed(self) -> bool:
        """Whether writing it changes the file."""
        return self.previous != self.content


def plan_tunnel_policy(
    user: str,
    console_port: int,
    *,
    sshd_config: Path = SSHD_CONFIG,
    dropin_dir: Path = SSHD_DROPIN_DIR,
    keys_dir: Path = TUNNEL_KEYS_DIR,
) -> SshdPolicy:
    """
    Decide where the tunnel account's ``Match`` block goes, and what the file becomes.

    Args:
        user: The tunnel account.
        console_port: The console's loopback port.
        sshd_config: sshd's main configuration file.
        dropin_dir: sshd's fragment directory.
        keys_dir: Where the account's key file is.

    Returns:
        The plan; nothing is written.

    Raises:
        NodeError: When a file on the way is a symlink.
    """
    block = tunnel_policy_block(user, console_port, keys_dir)
    dropin = dropin_dir / SSHD_DROPIN_NAME
    # No sshd_config at all is a distribution that keeps it under /usr (openSUSE's
    # /usr/etc/ssh), which includes the fragment directory itself; creating one
    # here would replace the vendor's whole configuration. Whether the fragment
    # is read is checked afterwards with sshd -T either way.
    main_missing = not sshd_config.exists() and not sshd_config.is_symlink()
    if dropin_dir.is_dir() and (main_missing or _includes(sshd_config, dropin)):
        header = (
            "# Generated by Noust: the account centrals' SSH tunnels log in as.\n"
            "# 'noust fleet authorize' writes this file; changes made here are replaced.\n"
        )
        return SshdPolicy(dropin, _read_no_follow(dropin), header + block)
    if main_missing:
        raise NodeError(
            f"sshd's configuration was not found ({sshd_config}, {dropin_dir})",
            details="Install OpenSSH's server (openssh-server), then authorize again.",
        )
    previous = _read_no_follow(sshd_config)
    base = _without_block(previous or "")
    # Last in the file: every line after a Match belongs to it.
    marked = f"{POLICY_BEGIN}\n{block}{POLICY_END}\n"
    content = f"{base}\n{marked}" if base else marked
    return SshdPolicy(sshd_config, previous, content)


def _write_policy(policy: SshdPolicy, text: str | None, fs: FileSystem) -> None:
    """
    Write a policy file, or remove it.

    Args:
        policy: The plan.
        text: The content, or None to remove the file.
        fs: The filesystem seam.
    """
    if text is None:
        fs.remove(policy.path, missing_ok=True)
        return
    try:
        mode = stat.S_IMODE(policy.path.lstat().st_mode)
    except FileNotFoundError:
        mode = SSHD_POLICY_MODE
    fs.write_text(policy.path, text, mode=mode)
    fs.chmod(policy.path, mode)


def reload_sshd(runner: CommandRunner) -> str | None:
    """
    Reload sshd so it reads its configuration again; live sessions survive a reload.

    Args:
        runner: The runner.

    Returns:
        The unit reloaded, or None when none is running (socket activation:
        the next connection starts sshd with the new configuration).

    Raises:
        NodeError: When the reload fails.
    """
    for unit in SSHD_UNITS:
        state = runner.run(["systemctl", "is-active", unit], timeout=SSHD_TIMEOUT)
        if state.stdout.strip() != "active":
            continue
        try:
            runner.run(["systemctl", "reload", unit], timeout=SSHD_TIMEOUT, check=True)
        except CommandError as exc:
            raise NodeError(
                f"sshd ({unit}) could not be reloaded",
                details=f"See 'journalctl -u {unit} -n 50'.",
                output=exc.details,
            ) from exc
        return unit
    return None


def tunnel_policy_problems(settings: SshdSettings, console_port: int, keys_dir: Path) -> list[str]:
    """
    Compare what sshd applies to the tunnel account with what Noust's block asks for.

    Args:
        settings: ``sshd -T -C user=<tunnel account>``.
        console_port: The console's loopback port.
        keys_dir: Where the account's key file is.

    Returns:
        One sentence per setting sshd applies differently: an earlier
        ``Match`` block or file set it first.
    """
    expected: list[tuple[str, object, object]] = [
        ("AllowTcpForwarding", settings.allow_tcp_forwarding, "local"),
        ("DisableForwarding", "yes" if settings.disable_forwarding else "no", "no"),
        ("AllowStreamLocalForwarding", settings.allow_stream_local_forwarding, "no"),
        ("PermitOpen", " ".join(settings.permit_open), f"127.0.0.1:{int(console_port)}"),
        ("PermitTTY", settings.permit_tty, "no"),
        ("X11Forwarding", settings.x11_forwarding, "no"),
        ("AllowAgentForwarding", settings.allow_agent_forwarding, "no"),
        ("ForceCommand", settings.force_command or "none", FORCED_COMMAND),
        ("AuthorizedKeysFile", " ".join(settings.authorized_keys_files), f"{keys_dir}/%u.keys"),
    ]
    return [
        f"sshd applies '{name} {actual}' to the tunnel account, not '{name} {wanted}': "
        "another Match block or configuration file sets it first."
        for name, actual, wanted in expected
        if actual != wanted
    ]


def apply_tunnel_policy(
    user: str,
    console_port: int,
    *,
    runner: CommandRunner,
    fs: FileSystem,
    sshd_config: Path = SSHD_CONFIG,
    dropin_dir: Path = SSHD_DROPIN_DIR,
    keys_dir: Path = TUNNEL_KEYS_DIR,
    dry_run: bool = False,
) -> SshdPolicy:
    """
    Write the tunnel account's ``Match`` block, check it, reload sshd and verify it applies.

    ``sshd -t`` validates the whole configuration before sshd is reloaded,
    and ``sshd -T -C user=<account>`` afterwards shows what sshd really
    applies to the account - reading the files is not enough, since an
    earlier file or ``Match`` wins. Any failure puts the file back as it was
    (and reloads again when it had reloaded), so a refused change leaves sshd
    exactly as it found it.

    Args:
        user: The tunnel account.
        console_port: The console's loopback port.
        runner: The runner.
        fs: The filesystem seam.
        sshd_config: sshd's main configuration file.
        dropin_dir: sshd's fragment directory.
        keys_dir: Where the account's key file is.
        dry_run: Plan only: nothing is written, tested or reloaded.

    Returns:
        What was written (or would be).

    Raises:
        NodeError: When sshd refuses the configuration, cannot be reloaded,
            or does not apply the block to the account. Details carry sshd's
            own words or the settings that differ.
    """
    policy = plan_tunnel_policy(
        user, console_port, sshd_config=sshd_config, dropin_dir=dropin_dir, keys_dir=keys_dir
    )
    if dry_run:
        return policy
    if policy.changed:
        _write_policy(policy, policy.content, fs)
    reloaded = False
    try:
        test = runner.run(["sshd", "-t"], timeout=SSHD_TIMEOUT)
        if not test.success:
            raise NodeError(
                "sshd refused the tunnel account's configuration; nothing was changed",
                details=f"The file {policy.path} was put back as it was. sshd said:",
                output=(test.stderr or test.stdout).strip(),
            )
        if policy.changed:
            reloaded = reload_sshd(runner) is not None
        problems = tunnel_policy_problems(
            read_sshd_settings(runner, sshd_config, user=user), console_port, keys_dir
        )
        if problems:
            raise NodeError(
                f"sshd does not apply Noust's restrictions to {user}",
                details="\n".join(
                    [
                        *problems,
                        f"{policy.path} was put back as it was. Find what sets these for "
                        f"{user} ('sshd -T -C user={user},host={EVALUATE_HOST},"
                        f"addr={EVALUATE_ADDR}' shows the result), remove it, and authorize "
                        "again.",
                    ]
                ),
            )
    except NodeError:
        if policy.changed:
            _write_policy(policy, policy.previous, fs)
            if reloaded:
                reload_sshd(runner)
        raise
    return policy


# ---------------------------------------------------------------------------
# Tokens
# ---------------------------------------------------------------------------


def token_base_name(central: str) -> str:
    """
    Name a central's token on this server.

    Args:
        central: The central's name.

    Returns:
        ``fleet-<central>``.
    """
    return f"fleet-{validate_central_name(central)}"


def _is_token_of(name: str, central: str) -> bool:
    """
    Report whether a token name is a given central's.

    Token names are unique for good (revoked ones included), so a central
    authorized again gets ``fleet-<central>.2``, ``.3``...

    Args:
        name: A token name.
        central: The central's name.

    Returns:
        True for ``fleet-<central>`` and ``fleet-<central>.<n>``.
    """
    return re.fullmatch(re.escape(token_base_name(central)) + r"(?:\.[0-9]+)?", name) is not None


def live_fleet_tokens(tokens: TokenManager, central: str) -> list[dict[str, Any]]:
    """
    List a central's unrevoked fleet tokens on this server.

    Args:
        tokens: The token manager.
        central: The central's name.

    Returns:
        Their records.
    """
    return [
        record
        for record in tokens.list_api_tokens()
        if record["scope"] == FLEET_SCOPE
        and record["revoked_at"] is None
        and _is_token_of(str(record["name"]), central)
    ]


def next_token_name(tokens: TokenManager, central: str) -> str:
    """
    Pick the name of a central's next token: unique across every token ever issued.

    Args:
        tokens: The token manager.
        central: The central's name.

    Returns:
        ``fleet-<central>``, or ``fleet-<central>.<n>`` when that was used.
    """
    taken = {str(record["name"]) for record in tokens.list_api_tokens()}
    base = token_base_name(central)
    if base not in taken:
        return base
    number = 2
    while f"{base}.{number}" in taken:
        number += 1
    return f"{base}.{number}"


# ---------------------------------------------------------------------------
# Running on the central that issued the key
# ---------------------------------------------------------------------------


def issued_here(key: PublicKey, central: str) -> str | None:
    """
    Tell whether this server is the central that issued a key, and how that is known.

    A central does not enroll itself; ``noust fleet authorize`` pasted into
    the wrong terminal (the central's own, or ``docker exec`` into the central's
    container) would otherwise install the central's key on the central.
    Two signs, strongest first: this server holds that very key for one of
    its nodes (needs its secrets readable), or it is a central by that name
    managing nodes (works on a sealed, locked central: only names are read).

    Args:
        key: The key being authorized.
        central: The ``--name`` given.

    Returns:
        The reason, or None when nothing says this server is that central.
    """
    from noust.core.secrets import SecretStore, secrets_dir
    from noust.core.store import StoreError, get_store
    from noust.fleet.keys import NODES_NAMESPACE, NodeKeys

    try:
        nodes_dir = secrets_dir() / NODES_NAMESPACE
        registered = bool(get_store().list_nodes())
    except StoreError:
        # No store yet (a rehearsal does not create one): no fleet state, so
        # not a central.
        return None
    names = sorted(p.name for p in nodes_dir.iterdir() if p.is_dir()) if nodes_dir.is_dir() else []
    held = NodeKeys(SecretStore())
    for name in names:
        try:
            public = held.public_key(name)
        except (NodeError, ConfigError, SealError):
            # Sealed and locked, or not a key: the weaker sign below decides.
            continue
        if public is not None and public.fingerprint == key.fingerprint:
            return f"it holds this very key, for its node {name}"
    try:
        this = central_name()
    except NodeError:
        return None
    named = key.comment.removeprefix("noust-central@") if key.comment else ""
    manages = bool(names) or registered
    if manages and this in (named, central):
        return f"it is the central '{this}' and manages nodes"
    return None


def ceiling_in_force(store: NoustStore | None = None) -> FleetAccess:
    """
    Read this server's ceiling for a rehearsal or a report, where there may be no store yet.

    Not for enforcement: :func:`noust.fleet.policy.current_access` is, and it
    fails rather than guess.

    Args:
        store: The store; the process-wide one by default.

    Returns:
        The ceiling; the default when the store was never created (a
        ``--dry-run`` on a fresh server does not create it).
    """
    from noust.core.store import StoreError

    try:
        return current_access(store)
    except StoreError:
        return DEFAULT_ACCESS


# ---------------------------------------------------------------------------
# Authorize and deauthorize
# ---------------------------------------------------------------------------


@dataclass
class AuthorizeResult:
    """
    What ``noust fleet authorize`` did, and the code to paste into the central.

    Attributes:
        join_code: The code. It holds the token: shown once, like a token.
        central: The central's name.
        token_name: The token's name on this server.
        node_name: The name this server suggests for itself.
        ssh_user: The account the key was installed for.
        ssh_port: sshd's port.
        console_port: The console's loopback port.
        authorized_keys: The file the key line is in.
        key_fingerprint: The central key's fingerprint.
        host_key_fingerprint: This server's host key fingerprint.
        key_changed: False when the exact line was already there.
        replaced_tokens: Older tokens of this central, now revoked.
        access: This server's ceiling for its centrals, as now in force
            (:meth:`~noust.fleet.policy.FleetAccess.to_dict`).
        tunnel_account_created: Whether the tunnel account was created now.
        sshd_policy: The file holding the tunnel account's ``Match`` block,
            None for another account.
        moved_from: Other key files this central's lines were removed from
            (a central moving from root to the tunnel account), by its name
            or by the key ``--replace-root-key`` named.
        root_key_backup: The copy of root's ``authorized_keys`` kept before
            ``--replace-root-key`` took a line out of it.
        warnings: What the operator should know and could not be done: a
            central's tunnel key still in root's file, with the command that
            removes it.
    """

    join_code: str
    central: str
    token_name: str
    node_name: str
    ssh_user: str
    ssh_port: int
    console_port: int
    authorized_keys: str
    key_fingerprint: str
    host_key_fingerprint: str
    key_changed: bool
    replaced_tokens: list[str] = field(default_factory=list)
    access: dict[str, Any] = field(default_factory=dict)
    tunnel_account_created: bool = False
    sshd_policy: str | None = None
    moved_from: list[str] = field(default_factory=list)
    root_key_backup: str | None = None
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """
        Describe the result for ``--json``.

        Returns:
            Every field.
        """
        return asdict(self)


def _known_key_files(
    *,
    except_user: str | None,
    runner: CommandRunner | None,
    fs: FileSystem | None,
    sshd_config: Path,
    passwd: Callable[[str], pwd.struct_passwd],
    keys_dir: Path,
    root_keys: AuthorizedKeys | None = None,
) -> list[AuthorizedKeys]:
    """
    List the key files Noust may have put a central's line in: root's, and the tunnel account's.

    Args:
        except_user: Leave this account's file out.
        runner: The runner.
        fs: The filesystem seam.
        sshd_config: Read when ``sshd -T`` cannot run.
        passwd: Account lookup.
        keys_dir: Where the tunnel account's key file is.
        root_keys: Root's file when the caller already found it; looked up
            (``sshd -T``) otherwise.

    Returns:
        The editors of the files that exist.
    """
    files: list[AuthorizedKeys] = []
    if except_user != TUNNEL_USER:
        tunnel = tunnel_keys_file(TUNNEL_USER, keys_dir=keys_dir, fs=fs, runner=runner)
        if tunnel.path.exists():
            files.append(tunnel)
    if except_user != "root":
        editor = root_keys or _root_keys_file(
            runner=runner, fs=fs, sshd_config=sshd_config, passwd=passwd
        )
        if editor is not None and editor.path.exists():
            files.append(editor)
    return files


def _root_keys_file(
    *,
    runner: CommandRunner | None,
    fs: FileSystem | None,
    sshd_config: Path,
    passwd: Callable[[str], pwd.struct_passwd],
) -> AuthorizedKeys | None:
    """
    Build the editor of root's ``authorized_keys``, where 3.0 put centrals' keys.

    Args:
        runner: The runner.
        fs: The filesystem seam.
        sshd_config: Read when ``sshd -T`` cannot run.
        passwd: Account lookup.

    Returns:
        The editor, or None on a server without a root account.
    """
    try:
        root = passwd("root")
    except KeyError:
        return None
    return _authorized_keys_for(
        root, read_sshd_settings(runner, sshd_config, user="root"), fs, runner
    )


def _root_key_warnings(
    root_keys: AuthorizedKeys | None, *, keep: PublicKey | None, removing: PublicKey | None
) -> list[str]:
    """
    Warn about every central's tunnel key left in root's ``authorized_keys``.

    Args:
        root_keys: Root's file, None when there is no root account.
        keep: The key just authorized for root itself (``--ssh-user root``),
            which is meant to be there.
        removing: The key a rehearsal would remove, which will not be there.

    Returns:
        One warning per line, with the command that removes it.
    """
    if root_keys is None:
        return []
    try:
        found = root_tunnel_keys(root_keys.path, root_keys.read())
    except NodeError as exc:
        return [f"root's {root_keys.path} could not be checked ({exc.message}): {exc.details}"]
    expected = {(key.key_type, key.blob) for key in (keep, removing) if key is not None}
    return [line.warning() for line in found if (line.key_type, line.blob) not in expected]


def authorize(
    *,
    central_key: str,
    central: str,
    tokens: TokenManager,
    ensure_console: Callable[[], int],
    confirm_replace: Callable[[list[str]], bool],
    ssh_user: str = TUNNEL_USER,
    allow_root: bool = False,
    replace_root_key: str | None = None,
    access: FleetAccess | None = None,
    runner: CommandRunner | None = None,
    fs: FileSystem | None = None,
    host_key_file: Path = HOST_KEY_FILE,
    sshd_config: Path = SSHD_CONFIG,
    sshd_dropin_dir: Path = SSHD_DROPIN_DIR,
    tunnel_keys_dir: Path = TUNNEL_KEYS_DIR,
    passwd: Callable[[str], pwd.struct_passwd] = pwd.getpwnam,
    store: NoustStore | None = None,
    self_check: Callable[[PublicKey, str], str | None] | None = issued_here,
    progress: Progress | None = None,
    actor: str | None = None,
    dry_run: bool = False,
) -> AuthorizeResult:
    """
    Authorize a central on this server and build its join code.

    Every check runs before anything changes - the key, the name, whether
    this is the central that issued the key, sshd's settings for the
    account, the confirmation to replace an older token. Then: the console
    as a loopback service, the tunnel account and its sshd restrictions, the
    key line, the token and the ceiling. A token that cannot be issued puts
    the key file back as it was; sshd restrictions that do not apply are put
    back as they were.

    Args:
        central_key: The central's public key line for this node.
        central: The central's name.
        tokens: This server's token manager.
        ensure_console: Makes sure the console runs as a loopback service and
            returns its port; raises when it cannot.
        confirm_replace: Asked with the names of this central's live tokens,
            when there are any; False cancels before anything changes.
        ssh_user: The account the central logs in as: the tunnel account by
            default, created when missing.
        allow_root: Accept ``ssh_user="root"``. Its key, even restricted, can
            create Unix sockets as root (see the module docstring).
        replace_root_key: A public key to take out of root's
            ``authorized_keys`` once the new line is in place: the central's
            key as 3.0 installed it there (``noust node migrate-tunnel``
            prints it). Matched by the key, whatever the line's comment, and
            a 0600 copy of the file is kept. Refused with ``ssh_user="root"``.
        access: This server's new ceiling for its centrals; None keeps the
            one in force (admin when none was ever set).
        runner: The runner ``sshd``, ``useradd``, ``systemctl`` and ``chown`` go through.
        fs: The filesystem seam.
        host_key_file: This server's ed25519 host key.
        sshd_config: sshd's main configuration, also read when ``sshd -T``
            cannot run.
        sshd_dropin_dir: sshd's fragment directory.
        tunnel_keys_dir: Where the tunnel account's key file is.
        passwd: Account lookup.
        store: The store the ceiling is kept in; the process-wide one by default.
        self_check: Says why this server is the central that issued the key
            (:func:`issued_here`), or None to skip the check.
        progress: Told when each step starts: ``(step, total, what)``.
        actor: Who authorizes, recorded with the ceiling.
        dry_run: Rehearse: every check still runs, but nothing is written,
            no account is created, sshd is not touched and no token is minted
            or revoked. The join code carries :data:`DRY_RUN_TOKEN` instead,
            which nothing accepts.

    Returns:
        What was done (or, under a rehearsal, what would be) and the join code.

    Raises:
        NodeError: When any input or precondition is wrong, the operator
            cancels, or a step fails (what it had changed is put back).
    """
    central = validate_central_name(central)
    key = parse_public_key(central_key, what="central key")
    user = validate_ssh_user(ssh_user)
    tunnel = user == TUNNEL_USER
    if user == "root" and not allow_root:
        raise NodeError(
            "Refusing to authorize a central as root without --i-understand",
            details=(
                f"Use the default tunnel account ({TUNNEL_USER}) instead. A key in root's "
                "authorized_keys, even restricted, can make sshd create a Unix socket as "
                "root anywhere (ssh -R /etc/nologin:...), because permitlisten only limits "
                f"TCP. {TUNNEL_USER} cannot, and its sshd block refuses Unix sockets. "
                "Pass --i-understand to authorize root anyway."
            ),
        )
    replace_key = (
        parse_public_key(replace_root_key, what="key to take out of root's authorized_keys")
        if replace_root_key is not None
        else None
    )
    if replace_key is not None and user == "root":
        raise NodeError(
            "--replace-root-key cannot be used with --ssh-user root",
            details="It takes a central's old key out of root's file; this installs one there.",
        )
    runner = runner or get_runner()
    report = progress or (lambda step, total, what: None)
    total = 6 if tunnel else 4

    reason = self_check(key, central) if self_check is not None else None
    if reason is not None:
        raise NodeError(
            "This server is the central that issued this key",
            details=(
                f"A central does not enroll itself: {reason}. Run the command on the server "
                f"you want to add, not here (this is {local_node_name()}). Pass --allow-self "
                "only to test a central against itself."
            ),
        )

    try:
        host_key = parse_public_key(
            host_key_file.read_text(encoding="utf-8"), what="SSH host key of this server"
        )
    except FileNotFoundError as exc:
        raise NodeError(
            f"This server has no ed25519 SSH host key ({host_key_file})",
            details="Generate the missing host keys with 'ssh-keygen -A', reload sshd, "
            "and authorize again.",
        ) from exc

    report(1, total, f"Checking sshd for {user}")
    if tunnel:
        try:
            existing: pwd.struct_passwd | None = passwd(user)
        except KeyError:
            existing = None
        groups = _groups_of(existing) if existing is not None else (user,)
    else:
        existing = _account(user, passwd)
        groups = _groups_of(existing)
    settings = read_sshd_settings(runner, sshd_config, user=user)
    blockers = sshd_blockers(settings, user, groups, tunnel=tunnel)
    if blockers:
        raise NodeError("sshd would refuse the central's tunnel", details="\n".join(blockers))
    if tunnel and existing is not None:
        # Checked again when the account is prepared; here, before anything changes.
        _refuse_login_shell(existing)

    older = live_fleet_tokens(tokens, central)
    if older and not confirm_replace([str(record["name"]) for record in older]):
        raise NodeError("Cancelled: nothing was changed")

    report(2, total, "Making sure the console runs on 127.0.0.1 as a service")
    console_port = ensure_console()

    created = False
    policy: SshdPolicy | None = None
    if tunnel:
        report(3, total, f"Preparing the tunnel account {user}")
        account, created = ensure_tunnel_account(
            user, runner=runner, passwd=passwd, dry_run=dry_run
        )
        report(4, total, f"Restricting {user} in sshd")
        policy = apply_tunnel_policy(
            user,
            console_port,
            runner=runner,
            fs=fs or get_fs(),
            sshd_config=sshd_config,
            dropin_dir=sshd_dropin_dir,
            keys_dir=tunnel_keys_dir,
            dry_run=dry_run,
        )
        keys_file = tunnel_keys_file(user, keys_dir=tunnel_keys_dir, fs=fs, runner=runner)
    else:
        account = existing if existing is not None else _account(user, passwd)
        keys_file = _authorized_keys_for(account, settings, fs, runner)

    line = authorized_key_line(central, key, console_port)
    report(total - 1, total, f"Installing the central's key in {keys_file.path}")
    warnings: list[str] = []
    moved_from: list[str] = []
    backup: Path | None = None
    root_keys = (
        keys_file
        if user == "root"
        else _root_keys_file(runner=runner, fs=fs, sshd_config=sshd_config, passwd=passwd)
    )
    if dry_run:
        # Nothing is minted or written: the console step above already
        # refused to touch the machine under a rehearsal (it threads dry_run
        # through to 'noust web enable'), and this is the token store's own
        # chokepoint for the same promise, since it has no fs/runner seam.
        changed = keys_file.would_change(line, central)
        report(total, total, f"Issuing the token {next_token_name(tokens, central)}")
        issued = {"token": DRY_RUN_TOKEN, "name": next_token_name(tokens, central)}
        in_force = access or ceiling_in_force(store)
        if replace_key is not None and root_keys is not None and root_keys.holds_key(replace_key):
            moved_from.append(str(root_keys.path))
    else:
        # Locked from the read this rollback would restore through the
        # write that might undo it, so a concurrent authorize/deauthorize
        # for another central can never land between them and be clobbered.
        with _locked_for_write(keys_file.path):
            previous = keys_file.read()
            changed = keys_file.install(line, central)
            report(total, total, f"Issuing the token {next_token_name(tokens, central)}")
            try:
                issued = tokens.create_fleet_token(next_token_name(tokens, central))
            except SecurityError as exc:
                if changed:
                    keys_file.write(previous)
                raise NodeError(
                    "Could not create the fleet token", details=exc.details or exc.message
                ) from exc
        for record in older:
            tokens.revoke_api_token(int(record["id"]))
        in_force = set_access(access, actor=actor, store=store) if access else current_access(store)
        # One central, one account: the line it had in another account's
        # file (root's, before 3.1) goes, now that the new one is in place.
        for other in _known_key_files(
            except_user=user,
            runner=runner,
            fs=fs,
            sshd_config=sshd_config,
            passwd=passwd,
            keys_dir=tunnel_keys_dir,
            root_keys=root_keys,
        ):
            try:
                if other.remove(central):
                    moved_from.append(str(other.path))
            except NodeError as exc:
                warnings.append(
                    f"The central's old line in {other.path} could not be removed "
                    f"({exc.message}); remove it by hand: {exc.details}"
                )
        if replace_key is not None and root_keys is not None:
            try:
                backup = root_keys.remove_key(replace_key)
            except (NodeError, OSError) as exc:
                warnings.append(
                    f"The key {replace_key.fingerprint} could not be taken out of "
                    f"{root_keys.path} ({exc}); remove it by hand: "
                    f"{key_removal_command(root_keys.path, replace_key.blob)}"
                )
            if backup is not None and str(root_keys.path) not in moved_from:
                moved_from.append(str(root_keys.path))
    # Whatever was asked: a tunnel key left in root's file is the hole the
    # tunnel account closes, and the operator hears of every one.
    warnings.extend(
        _root_key_warnings(
            root_keys,
            keep=key if user == "root" else None,
            removing=replace_key if dry_run else None,
        )
    )

    code = JoinCode(
        ssh_host_key=host_key.bare,
        ssh_user=account.pw_name,
        ssh_port=settings.port,
        console_port=console_port,
        token=str(issued["token"]),
        noust_version=__version__,
        central_key_fp=key.fingerprint,
        node_name=local_node_name(),
        token_name=str(issued["name"]),
        central=central,
    )
    return AuthorizeResult(
        join_code=code.encode(),
        central=central,
        token_name=str(issued["name"]),
        node_name=local_node_name(),
        ssh_user=account.pw_name,
        ssh_port=settings.port,
        console_port=console_port,
        authorized_keys=str(keys_file.path),
        key_fingerprint=key.fingerprint,
        host_key_fingerprint=host_key.fingerprint,
        key_changed=changed,
        replaced_tokens=[str(record["name"]) for record in older],
        access=in_force.to_dict(),
        tunnel_account_created=created,
        sshd_policy=str(policy.path) if policy is not None else None,
        moved_from=moved_from,
        root_key_backup=str(backup) if backup is not None else None,
        warnings=warnings,
    )


@dataclass
class DeauthorizeResult:
    """
    What ``noust fleet deauthorize`` removed.

    Attributes:
        central: The central's name.
        authorized_keys: The key files looked at.
        removed_keys: Key lines removed.
        revoked_tokens: Token names revoked.
    """

    central: str
    authorized_keys: list[str]
    removed_keys: int
    revoked_tokens: list[str]

    def to_dict(self) -> dict[str, Any]:
        """
        Describe the result for ``--json``.

        Returns:
            Every field.
        """
        return asdict(self)


def deauthorize(
    *,
    central: str,
    tokens: TokenManager,
    ssh_user: str | None = None,
    runner: CommandRunner | None = None,
    fs: FileSystem | None = None,
    sshd_config: Path = SSHD_CONFIG,
    tunnel_keys_dir: Path = TUNNEL_KEYS_DIR,
    passwd: Callable[[str], pwd.struct_passwd] = pwd.getpwnam,
    dry_run: bool = False,
) -> DeauthorizeResult:
    """
    Stop trusting a central: remove its key lines and revoke its tokens.

    The central's tunnel stops at its next connection, and its requests stop
    authenticating at once. The tunnel account and its sshd block stay: they
    serve every central, and hold no key once the last one is gone.

    Args:
        central: The central's name.
        tokens: This server's token manager.
        ssh_user: Only this account's key file; None looks in every file
            Noust writes (the tunnel account's and root's).
        runner: The runner.
        fs: The filesystem seam.
        sshd_config: Read when ``sshd -T`` cannot run.
        tunnel_keys_dir: Where the tunnel account's key file is.
        passwd: Account lookup.
        dry_run: Rehearse: report what would be removed and revoked without
            touching a key file or the token store.

    Returns:
        What was removed (or, under a rehearsal, what would be).

    Raises:
        NodeError: When the name or the account is invalid.
    """
    central = validate_central_name(central)
    if ssh_user is None:
        files = _known_key_files(
            except_user=None,
            runner=runner,
            fs=fs,
            sshd_config=sshd_config,
            passwd=passwd,
            keys_dir=tunnel_keys_dir,
        )
    elif validate_ssh_user(ssh_user) == TUNNEL_USER:
        files = [tunnel_keys_file(TUNNEL_USER, keys_dir=tunnel_keys_dir, fs=fs, runner=runner)]
    else:
        account = _account(ssh_user, passwd)
        files = [
            _authorized_keys_for(
                account, read_sshd_settings(runner, sshd_config, user=account.pw_name), fs, runner
            )
        ]
    live = live_fleet_tokens(tokens, central)
    paths = [str(editor.path) for editor in files]
    if dry_run:
        return DeauthorizeResult(
            central=central,
            authorized_keys=paths,
            removed_keys=sum(len(editor.lines_of(central)) for editor in files),
            revoked_tokens=[str(record["name"]) for record in live],
        )
    removed = sum(editor.remove(central) for editor in files)
    revoked: list[str] = []
    for record in live:
        tokens.revoke_api_token(int(record["id"]))
        revoked.append(str(record["name"]))
    return DeauthorizeResult(
        central=central,
        authorized_keys=paths,
        removed_keys=removed,
        revoked_tokens=revoked,
    )
