# Copyright (c) 2024-2026 Yago Lopez Prado
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Debian and Ubuntu: apt, dpkg, needrestart and unattended-upgrades.

Three facts about apt shape everything here:

- It has no "security only" switch. The security subset is the packages whose
  candidate comes from a ``-security`` suite, found by simulating the upgrade,
  and applied by naming them.
- ``apt list --upgradable`` is not the list. Ubuntu's phased updates show up
  there and are not installed by ``apt-get upgrade``, so the list would promise
  what the upgrade will not do. The simulation is what the upgrade would do.
- A question from dpkg (a modified conffile) or from needrestart hangs a job
  that has no terminal, silently. Every command runs with the answers already
  given: keep the local file, list services instead of restarting them.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Sequence
from datetime import datetime, timezone

from noust.managers.server.errors import ServerError
from noust.managers.server.host import (
    natural_key,
    newest_installed_kernel,
    read_text,
    running_kernel,
)
from noust.managers.server.pkg.base import (
    COMMON_ENV,
    INSTALL_TIMEOUT,
    LIST_TIMEOUT,
    LOCK_WAIT_SECONDS,
    NEEDRESTART_TIMEOUT,
    REFRESH_TIMEOUT,
    AutoUpdates,
    PackageBackend,
    PackageUpdate,
    PendingUpdates,
    RebootStatus,
    RestartProbe,
    UpdateScope,
    env_with,
    file_age_seconds,
    iso_from_mtime,
)

#: ``Inst bash [5.2.21-2ubuntu4] (5.2.21-2ubuntu4.1 Ubuntu:24.04/noble-updates [amd64])``.
#: The bracket after the name is absent for a package that is new to the machine;
#: the origins are separated by ``, `` when a version is in several suites.
_INST = re.compile(r"^Inst (\S+)(?: \[([^\]]+)\])? \((\S+) (.*?)(?: \[([^\]]+)\])?\)$")

#: ``Remv libold [1.0-1]``, optionally followed by what replaces it.
_REMV = re.compile(r"^Remv (\S+)")

#: ``Unattended-Upgrade::Allowed-Origins:: "${distro_id}:${distro_codename}-security";``.
_CONFIG_LINE = re.compile(r'^(\S+)\s+"(.*)";$')

#: The file the ``unattended-upgrades`` package's own dialog writes, so the
#: state is the same whoever turned it on.
AUTO_UPGRADES_FILE = "20auto-upgrades"

#: Noust's own drop-in, present only while the operator wants every update and
#: not just the security ones: apt merges list options across files, so adding
#: an origin is possible and removing one is not, which is why the default
#: origins stay untouched and this file adds ``-updates`` to them.
ALL_UPDATES_FILE = "52noust-unattended-upgrades"

_HEADER = "// Generated by Noust. Changes made here are replaced.\n"

_KERNEL_PREFIXES = ("linux-image",)


def parse_upgrade_simulation(text: str) -> tuple[list[PackageUpdate], list[str]]:
    """
    Read the output of ``apt-get -s upgrade``.

    Args:
        text: The simulation's output.

    Returns:
        The updates (a package new to the machine has ``installed=None``), and
        the packages kept back.
    """
    packages: list[PackageUpdate] = []
    kept_back: list[str] = []
    in_kept_back = False
    for line in text.splitlines():
        if line.startswith("The following packages have been kept back:"):
            in_kept_back = True
            continue
        if in_kept_back:
            if line.startswith("  "):
                kept_back.extend(line.split())
                continue
            in_kept_back = False
        match = _INST.match(line)
        if not match:
            continue
        name, installed, candidate, origin, _arch = match.groups()
        suites = [part.split("/", 1)[-1] for part in origin.split(", ")]
        packages.append(
            PackageUpdate(
                name=name,
                installed=installed,
                candidate=candidate,
                security=any(suite.endswith("-security") for suite in suites),
                kernel=name.startswith(_KERNEL_PREFIXES),
                origin=origin,
            )
        )
    return packages, kept_back


def parse_removals(text: str) -> list[str]:
    """
    Read which packages a simulated upgrade would remove.

    Args:
        text: The simulation's output.

    Returns:
        The package names on its ``Remv`` lines.
    """
    return [m.group(1) for line in text.splitlines() if (m := _REMV.match(line))]


def parse_config_dump(text: str) -> dict[str, list[str]]:
    """
    Read ``apt-config dump`` into a mapping.

    Args:
        text: Its output.

    Returns:
        Each key with every value it was given, in order. List options
        (``Allowed-Origins::``) have several.
    """
    values: dict[str, list[str]] = {}
    for line in text.splitlines():
        match = _CONFIG_LINE.match(line.strip())
        if match:
            values.setdefault(match.group(1), []).append(match.group(2))
    return values


def parse_needrestart(text: str) -> dict[str, list[str]]:
    """
    Read ``needrestart -b``, the batch format of its README.

    Args:
        text: Its output.

    Returns:
        Each ``NEEDRESTART-<KEY>`` with every value it printed, keyed without
        the prefix (``KSTA``, ``SVC``...).
    """
    fields: dict[str, list[str]] = {}
    for line in text.splitlines():
        key, sep, value = line.partition(": ")
        if sep and key.startswith("NEEDRESTART-"):
            fields.setdefault(key.removeprefix("NEEDRESTART-"), []).append(value.strip())
    return fields


class AptBackend(PackageBackend):
    """Updates through apt-get, and the state of unattended-upgrades."""

    name = "apt"
    LOCK_PROCESSES = (
        "apt",
        "dpkg",
        "unattended-upgr",
        "packagekitd",
        "aptd",
        "cloud-init",
    )
    LOCK_FILES = (
        "/var/lib/dpkg/lock-frontend",
        "/var/lib/dpkg/lock",
        "/var/lib/apt/lists/lock",
        "/var/cache/apt/archives/lock",
    )

    def env(self) -> dict[str, str]:
        return env_with(
            COMMON_ENV,
            {
                "DEBIAN_FRONTEND": "noninteractive",
                "APT_LISTCHANGES_FRONTEND": "none",
                # List the services that need a restart and touch none of them:
                # needrestart's behaviour under a non-interactive apt has
                # changed between versions, and Noust never relies on it to
                # restart anything.
                "NEEDRESTART_MODE": "l",
            },
        )

    # -- listing --------------------------------------------------------------

    def list_updates(self) -> PendingUpdates:
        result = self.probe(
            ["apt-get", "-s", "-o", "Debug::NoLocking=1", "--with-new-pkgs", "upgrade"],
            timeout=LIST_TIMEOUT,
        )
        self.require(
            result,
            "Could not list the pending updates",
            "apt could not simulate the upgrade. Run 'apt-get update' and try again.",
        )
        packages, kept_back = parse_upgrade_simulation(result.stdout)

        holds = self.probe(["apt-mark", "showhold"]).stdout.split()
        audit = self.probe(["dpkg", "--audit"])
        now = datetime.now(timezone.utc)
        return PendingUpdates(
            packages=packages,
            kept_back=kept_back,
            holds=holds,
            checked_at=now.isoformat(),
            lists_age_seconds=self._lists_age(now.timestamp()),
            security_scope=True,
            broken=bool(audit.stdout.strip()),
        )

    def _lists_age(self, now: float) -> int | None:
        """
        Age of the package lists.

        Args:
            now: The current time.

        Returns:
            Seconds since apt last refreshed them, from the newest timestamp
            apt keeps, or from the lists directory when it keeps none.
        """
        for stamp in ("update-success-stamp", "update-stamp"):
            age = file_age_seconds(self.host.apt_periodic / stamp, now)
            if age is not None:
                return age
        return file_age_seconds(self.host.apt_lists, now)

    def removals(self, scope: UpdateScope, *, full: bool) -> list[str]:
        if scope is not UpdateScope.ALL or not full:
            return []
        result = self.probe(
            ["apt-get", "-s", "-o", "Debug::NoLocking=1", "full-upgrade"], timeout=LIST_TIMEOUT
        )
        self.require(result, "Could not simulate the full upgrade")
        return parse_removals(result.stdout)

    # -- acting ---------------------------------------------------------------

    def refresh_argv(self) -> list[str]:
        # --error-on=any: without it apt exits 0 when a mirror failed, the lists
        # stay old, and nobody is told.
        return [
            "apt-get",
            "update",
            "-q",
            "-o",
            "APT::Color=0",
            "-o",
            "Acquire::Retries=1",
            "--error-on=any",
        ]

    def refresh_timeout(self) -> int:
        return REFRESH_TIMEOUT

    def _apply_base(self) -> list[str]:
        """
        Options every applying command shares.

        Returns:
            ``apt-get`` with the answers to dpkg's questions already given:
            keep the operator's configuration files and the maintainer's for the
            ones nobody touched, wait for a lock rather than fail, no pty.
        """
        return [
            "apt-get",
            "-y",
            "-q",
            "-o",
            f"DPkg::Lock::Timeout={LOCK_WAIT_SECONDS}",
            "-o",
            "Dpkg::Options::=--force-confdef",
            "-o",
            "Dpkg::Options::=--force-confold",
            "-o",
            "Dpkg::Use-Pty=0",
        ]

    def upgrade_argv(self, scope: UpdateScope, packages: Sequence[str], *, full: bool) -> list[str]:
        base = self._apply_base()
        if scope is UpdateScope.ALL:
            if full:
                return [*base, "full-upgrade"]
            # What "apt upgrade" does: new dependencies, never a removal, and
            # kernel meta-packages are not left held back.
            return [*base, "--with-new-pkgs", "upgrade"]
        if not packages:
            raise ServerError(
                "There are no security updates to install",
                "Refresh the package lists first; the list of pending updates has none marked "
                "as security.",
            )
        # apt has no security-only switch: the packages are named. --no-remove
        # because installing a named package can resolve a conflict by removing
        # another, which is not what "security updates" promised.
        return [*base, "install", "--only-upgrade", "--no-remove", *packages]

    def install_argv(self, packages: Sequence[str]) -> list[str]:
        return ["apt-get", "install", "-y", *packages]

    def repair_commands(self) -> list[list[str]]:
        return [
            ["dpkg", "--configure", "-a"],
            ["apt-get", "-f", "install", "-y"],
        ]

    def clean_cache_argv(self) -> list[str] | None:
        return ["apt-get", "clean"]

    # -- reboot and services ----------------------------------------------------

    def restart_probe(self) -> RestartProbe:
        packages: list[str] = []
        reasons: list[str] = []
        sources: list[str] = []
        since: str | None = None

        flag = self.host.reboot_required
        if flag.exists():
            sources.append("reboot-required")
            since = iso_from_mtime(flag)
            listed = read_text(self.host.reboot_required_pkgs) or ""
            for name in listed.split():
                if name not in packages:
                    packages.append(name)
            reasons.append("An installed update left the reboot-required flag")

        services: list[str] = []
        available = self.runner.exists("needrestart")
        if available:
            result = self.runner.run(
                ["needrestart", "-b"], env=self.env(), timeout=NEEDRESTART_TIMEOUT
            )
            fields = parse_needrestart(result.stdout)
            if not fields and not result.success:
                available = False
            services = [unit for unit in fields.get("SVC", []) if unit]
            kernel_state = int((fields.get("KSTA") or ["0"])[0] or 0)
            if kernel_state >= 2:
                sources.append("needrestart")
                current = (fields.get("KCUR") or [""])[0]
                expected = (fields.get("KEXP") or [""])[0]
                reasons.append(
                    f"The running kernel is {current}; {expected} is installed"
                    if current and expected
                    else "A newer kernel is installed than the one running"
                )
            microcode_state = int((fields.get("UCSTA") or ["0"])[0] or 0)
            if microcode_state >= 2:
                sources.append("needrestart")
                reasons.append("The processor microcode was updated")
        else:
            newest = newest_installed_kernel(self.host)
            running = running_kernel()
            if newest and newest != running and natural_key(newest) > natural_key(running):
                sources.append("kernel")
                reasons.append(f"The running kernel is {running}; {newest} is installed")

        required = bool(sources)
        return RestartProbe(
            reboot=RebootStatus(
                required=required,
                packages=tuple(packages),
                reasons=tuple(reasons),
                since=since,
                source=", ".join(dict.fromkeys(sources)),
            ),
            services=tuple(services),
            available=available,
        )

    # -- automatic updates -------------------------------------------------------

    def auto_status(self) -> AutoUpdates:
        package = self.probe(["dpkg-query", "-W", "-f=${db:Status-Abbrev}", "unattended-upgrades"])
        installed = package.stdout.strip().startswith("ii")
        config = parse_config_dump(self.probe(["apt-config", "dump"]).stdout)

        def scalar(key: str) -> str:
            values = config.get(key) or [""]
            return values[-1]

        configured = scalar("APT::Periodic::Unattended-Upgrade") not in ("", "0")
        origins = config.get("Unattended-Upgrade::Allowed-Origins::", [])
        timers = self.probe(
            ["systemctl", "is-enabled", "apt-daily.timer", "apt-daily-upgrade.timer"]
        )
        timers_on = timers.success

        enabled = installed and configured and timers_on
        detail = ""
        if installed and configured and not timers_on:
            detail = (
                "unattended-upgrades is configured to run, but the apt-daily timers are "
                "disabled, so it never does."
            )
        return AutoUpdates(
            mechanism="unattended-upgrades",
            supported=True,
            installed=installed,
            enabled=enabled,
            security_only=(not any("-updates" in origin for origin in origins))
            if enabled
            else None,
            reboots=scalar("Unattended-Upgrade::Automatic-Reboot") == "true",
            last_run=iso_from_mtime(self.host.unattended_log),
            detail=detail,
        )

    def set_auto(
        self, enabled: bool, security_only: bool, on_line: Callable[[str], None]
    ) -> list[str]:
        steps: list[str] = []
        status = self.auto_status()
        directory = self.host.apt_conf_d

        if enabled and not status.installed:
            self.stream(
                self.install_argv(["unattended-upgrades"]),
                on_line,
                timeout=INSTALL_TIMEOUT,
                message="Could not install unattended-upgrades",
            )
            steps.append("Installed unattended-upgrades")

        self._write_conf(
            directory / AUTO_UPGRADES_FILE,
            f'APT::Periodic::Update-Package-Lists "1";\n'
            f'APT::Periodic::Unattended-Upgrade "{1 if enabled else 0}";\n',
        )
        steps.append(
            f"Set APT::Periodic::Unattended-Upgrade to {1 if enabled else 0} in "
            f"{directory / AUTO_UPGRADES_FILE}"
        )

        extra = directory / ALL_UPDATES_FILE
        if enabled and not security_only:
            self._write_conf(
                extra,
                'Unattended-Upgrade::Allowed-Origins {\n    "${distro_id}:${distro_codename}-updates";\n};\n',
            )
            steps.append(f"Allowed the -updates suite in {extra}")
        elif extra.exists():
            self.fs.remove(extra)
            steps.append(f"Removed {extra}, so only security updates are applied")

        if enabled:
            result = self.runner.run(
                ["systemctl", "enable", "--now", "apt-daily.timer", "apt-daily-upgrade.timer"],
                timeout=INSTALL_TIMEOUT // 10,
            )
            self.require(result, "Could not enable the apt-daily timers")
            steps.append("Enabled apt-daily.timer and apt-daily-upgrade.timer")

        # Another file of apt.conf.d can have the last word, and a setting that
        # was written and does not take effect is worse than one that was refused.
        after = self.auto_status()
        if enabled and not after.enabled:
            raise ServerError(
                "The setting was written but is not in effect",
                after.detail
                or "Another file in /etc/apt/apt.conf.d sets APT::Periodic::Unattended-Upgrade "
                "after this one. Run 'apt-config dump | grep Unattended' to see which.",
                output="\n".join(steps),
            )
        return steps

    def _write_conf(self, path, content: str) -> None:
        """
        Write one apt configuration file, keeping what an operator wrote before.

        Args:
            path: The file.
            content: What to write, after Noust's header.
        """
        body = _HEADER + content
        try:
            previous = path.read_text(encoding="utf-8")
        except OSError:
            previous = None
        if previous is not None and previous != body:
            backup = path.with_name(path.name + ".noust-bak")
            if not backup.exists():
                self.fs.write_text(backup, previous)
        self.fs.write_text(path, body)


__all__ = [
    "AUTO_UPGRADES_FILE",
    "AptBackend",
    "parse_config_dump",
    "parse_needrestart",
    "parse_removals",
    "parse_upgrade_simulation",
]
