# Copyright (c) 2024-2026 Yago Lopez Prado
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
An application's site: written, kept or removed in one place, and its certificate.

Every deployer writes the web server file of the application it deploys, and
every one of them used to decide on its own whether it could. Only
``BaseDeployer`` respected a site the operator wrote by hand (a file without
the "Generated by Noust" marker): Docker Compose replaced it on every deploy,
deleted it to put TLS in, and removed it with the application; a monorepo
overwrote it. The guard lives here, so there is one check and not six.

A site the operator wrote is never rewritten and never deleted. What Noust
would need it to contain - every name the application answers on - is
checked and reported as an actionable warning instead.

The certificate half is what :mod:`noust.deployers.domains` relies on to give
an application aliases and redirects: :class:`ServesDomains` is the capability
it asks for, whatever the deployer's class.
"""

from __future__ import annotations

import sqlite3
from collections.abc import Callable
from typing import TYPE_CHECKING, Any, Literal, Protocol, runtime_checkable

from noust.core.exceptions import CertificateError, DeploymentError, NoustError, ValidationError
from noust.core.fs import FileSystem
from noust.core.store import DomainKind

if TYPE_CHECKING:
    from noust.core.logger import Logger
    from noust.core.store import NoustStore
    from noust.managers.cert_manager import CertManager
    from noust.managers.webserver import WebServerManager

__all__ = [
    "RemoveOutcome",
    "ServesDomains",
    "WriteOutcome",
    "certificate_names",
    "has_certificate",
    "is_operator_site",
    "obtain_certificate",
    "refresh_app_site",
    "remove_app_site",
    "write_app_site",
    "write_template_site",
]

#: What writing a site did.
WriteOutcome = Literal["written", "kept_operator"]

#: What removing a site did.
RemoveOutcome = Literal["removed", "kept_operator", "absent"]

#: A site file is world-readable, like every file nginx ships with.
_SITE_MODE = 0o644


@runtime_checkable
class ServesDomains(Protocol):
    """
    A deployer that can serve an application on more than one name.

    What :mod:`noust.deployers.domains` needs to add an alias or a redirect:
    render the site again from what is deployed, tell whether a certificate
    is on disk, and order one covering every name the store records.
    """

    def refresh_site(self, *, with_ssl: bool) -> None:
        """Render the deployed application's site again, test it and load it."""
        ...

    def has_certificate(self) -> bool:
        """Tell whether a certificate lineage for the application is on disk."""
        ...

    def obtain_certificate(self) -> object:
        """Order a certificate covering every name the application answers on."""
        ...

    def webserver_manager(self) -> WebServerManager:
        """Return the manager of the web server that serves the application."""
        ...


def is_operator_site(manager: WebServerManager, domain: str) -> bool:
    """
    Tell whether a domain's site exists and was written by someone other than Noust.

    Args:
        manager: The web server manager the site lives in.
        domain: The application's domain.

    Returns:
        True when the file exists without Noust's marker.
    """
    return bool(manager.site_exists(domain)) and not manager.site_is_noust(domain)


def write_app_site(
    domain: str,
    render: Callable[[], str],
    *,
    logger: Logger,
    manager: WebServerManager | None = None,
    fs: FileSystem | None = None,
) -> WriteOutcome:
    """
    Write an application's site from text, unless the operator wrote it.

    For deployers that render their configuration themselves (a monorepo).
    ``render`` is only called when the file is going to be written, so a kept
    site costs nothing to produce.

    Args:
        domain: The application's domain.
        render: Produces the configuration text.
        logger: Where a kept site is reported.
        manager: The web server manager; nginx by default.
        fs: The filesystem to write through; the manager's by default. A
            deployer passes its own, which is what a rehearsal records.

    Returns:
        ``written``, or ``kept_operator`` when the existing file is the
        operator's and was left as it is.

    Raises:
        OSError: When the file or its link cannot be written.
        NoustError: When the web server refuses to enable the site.
    """
    manager = manager or _nginx()
    if is_operator_site(manager, domain):
        _report_kept(manager, domain, logger)
        return "kept_operator"
    fs = fs or manager.fs
    path = manager.config_path(domain)
    fs.write_text(path, render(), mode=_SITE_MODE)
    if manager.backend.enable_site_program is None:
        fs.make_dir(manager.sites_enabled)
        fs.symlink(path, manager.sites_enabled / path.name)
    else:
        manager.enable_site(domain)
    return "written"


def write_template_site(
    manager: WebServerManager,
    domain: str,
    *,
    template: str,
    context: dict[str, Any],
    logger: Logger,
) -> WriteOutcome:
    """
    Write an application's site from one of Noust's templates, unless the operator wrote it.

    Through the manager's own create and update, which read the names the
    application answers on from the store, refuse a name another application
    holds and record the site.

    Args:
        manager: The web server manager.
        domain: The application's domain.
        template: The template, without ``.conf.j2``.
        context: Its variables.
        logger: Where a kept site is reported.

    Returns:
        ``written``, or ``kept_operator`` when the existing file is the
        operator's and was left as it is.
    """
    if is_operator_site(manager, domain):
        _report_kept(manager, domain, logger)
        return "kept_operator"
    if manager.site_exists(domain):
        manager.update_site(domain, template=template, context=context)
    else:
        manager.create_site(domain, template=template, context=context)
        manager.enable_site(domain)
    return "written"


def refresh_app_site(
    manager: WebServerManager,
    domain: str,
    write: Callable[[], WriteOutcome],
) -> WriteOutcome:
    """
    Write an application's site again, test the whole configuration, and reload.

    A failing test puts the previous file back, so a change the web server
    refuses never lingers on disk to fail the next reload of another site.

    Args:
        manager: The web server manager.
        domain: The application's domain.
        write: Writes the site (through :func:`write_template_site` or
            :func:`write_app_site`), without reloading.

    Returns:
        What ``write`` did. An operator's site is neither tested nor
        reloaded: nothing of it changed.

    Raises:
        ValidationError: The web server rejected the configuration; its own
            output is the details, and the previous file is back.
        DeploymentError: The configuration is valid and the reload failed.
    """
    previous = manager.get_site_config(domain) if manager.site_exists(domain) else None
    outcome = write()
    if outcome == "kept_operator":
        return outcome
    problem = manager.config_errors()
    if problem is not None:
        if previous is None:
            manager.delete_site(domain)
        else:
            manager.replace_site_config(domain, previous, validate=False)
        raise ValidationError(
            f"{manager.backend.name} rejected the new configuration of {domain}",
            details=problem,
        )
    if not manager.reload():
        raise DeploymentError(
            f"{manager.backend.name} did not reload the configuration of {domain}",
            details="The configuration is valid; see why the reload failed with: "
            f"systemctl status {manager.backend.name}",
        )
    return outcome


def remove_app_site(
    domain: str,
    *,
    logger: Logger,
    manager: WebServerManager | None = None,
) -> RemoveOutcome:
    """
    Remove an application's site, unless the operator wrote it.

    Args:
        domain: The application's domain.
        logger: Where a kept site is reported.
        manager: The web server manager; nginx by default.

    Returns:
        ``removed`` (and the web server reloaded), ``kept_operator`` when the
        file is the operator's and was left in place, or ``absent``.
    """
    manager = manager or _nginx()
    if not manager.site_exists(domain):
        return "absent"
    if is_operator_site(manager, domain):
        logger.warning(
            f"{domain} has a site configuration Noust did not write; it is left in place. "
            f"Remove it by hand if nothing should answer on {domain} any more: "
            f"noust site delete {domain}"
        )
        return "kept_operator"
    manager.disable_site(domain)
    manager.delete_site(domain)
    manager.reload()
    return "removed"


def certificate_names(store: NoustStore, domain: str, *, include_www: bool = False) -> list[str]:
    """
    List every name an application's certificate must cover, primary first.

    Args:
        store: The store holding the application's domains.
        domain: The application's primary domain.
        include_www: Add ``www.<domain>``, which ``--www`` asks for and a
            rehearsal has no row for.

    Returns:
        The names, redirects included: they are served on 443 as well.
    """
    names = [record.domain for record in store.list_domains(domain)] or [domain]
    if include_www and f"www.{domain}" not in names:
        names.append(f"www.{domain}")
    return names


def has_certificate(cert_manager: CertManager, domain: str) -> bool:
    """
    Tell whether a certificate lineage for a domain is on disk.

    Args:
        cert_manager: The certificate manager.
        domain: The primary domain, which names the lineage.

    Returns:
        True when certbot's live directory holds one.
    """
    try:
        return cert_manager.cert_exists(domain)
    except CertificateError:
        return False


def obtain_certificate(
    cert_manager: CertManager,
    store: NoustStore,
    domain: str,
    *,
    webserver: str,
    logger: Logger,
    include_www: bool = False,
) -> None:
    """
    Order a certificate covering every name an application answers on.

    ``CertManager.obtain`` reads the same rows when it places the order;
    they are listed here so the operator sees them.

    Args:
        cert_manager: The certificate manager.
        store: The store holding the application's domains.
        domain: The application's primary domain.
        webserver: ``nginx`` or ``apache``, whose certbot plugin is used.
        logger: Where the names are reported.
        include_www: Also cover ``www.<domain>``.

    Raises:
        CertificateError: When certbot fails, with its output.
    """
    logger.substep(f"Domain: {domain}")
    names = certificate_names(store, domain, include_www=include_www)
    additional = [name for name in names if name != domain]
    if additional:
        logger.substep(f"Including: {', '.join(additional)}")
    cert_manager.obtain(
        domain,
        nginx=webserver == "nginx",
        apache=webserver == "apache",
        additional_domains=additional or None,
    )


def _report_kept(manager: WebServerManager, domain: str, logger: Logger) -> None:
    """
    Say that the operator's site was kept, and what in it Noust would need.

    Args:
        manager: The web server manager.
        domain: The application's domain.
        logger: Where it is said.
    """
    logger.warning(
        f"{domain} has a site configuration Noust did not write; it is kept as it is. "
        "Check it still points at this application."
    )
    try:
        records = manager.store.list_domains(domain)
    except (NoustError, sqlite3.Error) as exc:
        logger.debug(f"Could not read the domains of {domain}: {exc}")
        return
    wanted = [r.domain for r in records if r.kind != DomainKind.REDIRECT.value]
    served = set(manager.served_names(domain))
    missing = [name for name in wanted if name not in served]
    if missing:
        logger.warning(
            f"Its server_name does not include {', '.join(missing)}, which Noust records "
            f"for {domain}; add them to {manager.config_path(domain)} or they are not "
            "served by it."
        )


def _nginx() -> WebServerManager:
    """
    Build the nginx manager a caller that names none gets.

    Returns:
        A manager over the real nginx tree.
    """
    from noust.managers.nginx_manager import NginxManager

    return NginxManager()
